// Standardized image prompt framework for My Sleepy Tale.
// Ensures visual consistency across all story thumbnails, blog images,
// share cards, and marketing content.

// Master style prefix — appended to EVERY image prompt
export const STYLE_PREFIX = 'Digital children\'s storybook illustration, soft watercolor textures, warm golden hour lighting, rounded gentle shapes, cozy bedtime palette with deep purples and warm ambers, age-appropriate and inviting, Pixar-meets-Ghibli warmth, no text on image, NO human faces or realistic human figures — use only illustrated animals, objects, landscapes, or abstract shapes, 16:9 aspect ratio';

// Style variants for different contexts
export const STYLES = {
  thumbnail: `${STYLE_PREFIX}, close-up scene, single focal point, vibrant but soft colors, suitable as a story cover`,
  blog: `${STYLE_PREFIX}, wide landscape composition, atmospheric, editorial quality, room for text overlay on left side`,
  share: `${STYLE_PREFIX}, portrait 9:16 ratio, dramatic lighting, bold composition, Instagram-story style`,
  marketing: `${STYLE_PREFIX}, clean composition, brand-friendly, warm gold and deep navy palette, professional but playful`,
};

// Generate a complete prompt from a scene description
export function buildPrompt(scene, style = 'thumbnail') {
  const prefix = STYLES[style] || STYLES.thumbnail;
  return `${prefix}. Scene: ${scene}`;
}

// All 99 story prompts — standardized for visual consistency
export const STORY_PROMPTS = {
  // ══════ WISDOM STORIES ══════
  krishna_squirrel: 'A tiny illustrated squirrel lovingly carrying a single grain of rice near a silver river at sunset, a gentle boy with a peacock feather crown softly petting its back, lush Indian village with temple spires in the background, fireflies glowing',
  prophet_camel: 'A kind bearded man in flowing white robes gently stroking the ears of a tall brown camel in a moonlit garden, palm trees and stars above, ancient Middle Eastern architecture, warm amber lantern light, peaceful and tender moment',
  jesus_birds: 'A gentle figure sitting cross-legged in a wildflower meadow with dozens of small brown birds perched on his hands and shoulders, soft lavender sunset sky, rolling green hills, one bird mid-flight approaching his open palm',
  buddha_swan: 'A young prince in golden robes carefully cradling a wounded white swan near a lotus pond, bamboo forest behind, golden sunlight filtering through leaves, dewdrops on lotus petals, compassion on the prince\'s face',
  guru_nanak_grain: 'A wise bearded man in a white turban kneeling in a golden wheat field sharing grain with villagers, warm sunset painting everything amber, a simple wooden cart nearby, Punjab countryside with mustard flowers',
  mahavir_ant: 'A gentle barefoot prince tiptoeing carefully over a line of tiny ants on a forest path, lush green jungle with dappled sunlight, butterflies and dragonflies in the air, the prince looking down with tender concern',
  jewish_noah: 'A large wooden ark floating on calm indigo waters under a magnificent double rainbow, pairs of illustrated animals — elephants, giraffes, doves — on the deck, fluffy clouds parting to reveal golden sunlight',
  sikh_water_carrier: 'A brave turbaned warrior kneeling beside a fallen soldier on a dusty battlefield, offering water from a leather pouch, golden sunset behind, compassion overcoming conflict, warm amber and dusty tones',
  hanuman_mountain: 'A powerful illustrated monkey warrior flying through dramatic orange and purple clouds carrying an entire mountain peak covered in glowing blue herbs, stars visible in the sky, epic and majestic scale',
  ram_golden_deer: 'A magical golden deer with shimmering crystal antlers leaping through a moonlit Indian forest, a noble prince watching from behind ancient banyan trees, fireflies and starlight, enchanted atmosphere',
  akbar_birbal_well: 'A clever smiling minister in a Mughal turban standing beside an ornate palace well, gesturing cleverly while an amused emperor watches from a carved marble balcony, warm lamplight, intricate Indian architecture',
  panchatantra_monkey_crocodile: 'A clever brown monkey sitting high on a fruit-laden mango tree branch, chatting with a friendly crocodile in the river below, tropical jungle backdrop, colorful parrots, warm afternoon light through canopy',
  panchatantra_crow_pitcher: 'A clever glossy black crow carefully dropping a smooth pebble into a clay water pitcher, water level rising, warm dusty village courtyard with terracotta pots, afternoon golden light, determination in the crow\'s eye',
  krishna_govardhan: 'A small blue-skinned boy cheerfully lifting an enormous green mountain on his little finger like an umbrella, villagers and decorated cows sheltering underneath from dramatic rain, rainbow forming in the background',
  akbar_birbal_lines: 'A clever minister in an ornate Mughal court drawing a long line on a marble floor next to a shorter one, the emperor leaning forward surprised, courtiers watching, ornate pillars and lanterns',
  ganesha_mouse: 'A gentle elephant-headed deity with a golden crown bending down warmly to speak with a tiny brown mouse, ornate Indian temple backdrop with oil lamps and flowers, warm sunset glow through carved stone windows',
  hindu_cow_sage: 'An old white-bearded sage in a forest hermitage gently bandaging the leg of a spotted deer by warm firelight, lush green forest clearing, clay hut with smoke rising, compassionate tender scene',
  krishna_butter: 'A mischievous illustrated blue-skinned toddler with butter smeared on his cheeks grinning up at his loving mother who pretends to scold him, cozy Indian village kitchen with hanging clay pots, warm golden lamplight',
  harishchandra_promise: 'A noble king in torn clothes walking away from a magnificent golden palace into a dramatic sunset, head held high with dignity, orange and purple sky, silhouette of the palace behind, sacrifice and honor',
  yudhishthira_half_truth: 'A golden war chariot slowly sinking to touch the ground on a vast battlefield, a crowned warrior looking down with profound sorrow, dramatic golden light cutting through dust clouds, epic Indian mythology scene',
  sudama_poha: 'A humble man in simple clothes nervously offering a tiny cloth bundle of rice to a magnificent king on a golden throne, the king rising to embrace him with tears of joy, ornate palace hall with oil lamps',
  draupadi_akshaya_patra: 'A graceful woman in a silk sari serving steaming food from a magical golden vessel in a forest clearing to hundreds of seated people, warm light radiating from the vessel, abundance from simplicity',
  karna_golden_armour: 'A muscular warrior standing in dramatic sunset light, peeling radiant golden armour from his own chest to offer to a disguised elder, the armour glowing like molten gold, sacrifice and honor',
  ram_shabari_berries: 'An elderly tribal woman with a wrinkled kind face offering small purple berries on a leaf plate to a noble prince who eats them with genuine joy, simple forest hut, warm firelight, devotion',
  hanuman_chest: 'A powerful monkey warrior dramatically tearing open his chest to reveal a glowing divine couple inside his heart, royal court gasping in wonder, golden light radiating outward, epic devotion scene',
  shiva_kannappa: 'A tribal hunter in the dark forest offering his own eye to a sacred stone linga, divine light suddenly appearing, raw devotion, southern Indian temple forest with ancient trees and moss',
  ram_vibhishana: 'A noble prince warmly embracing a trembling man who kneels before him while armored warriors watch in surprise, golden sunset light, Ramayana epic scene, compassion overcoming suspicion',
  sage_scorpion: 'An old sage sitting by a peaceful river at sunset, gently lifting a black scorpion from the water with his bare weathered hand, golden reflections on water, serene Indian riverside with banyan trees',
  krishna_hundred_chances: 'A serene blue-skinned figure standing perfectly calm in a grand royal court as an angry red-faced king shouts and gestures wildly, patience personified, dramatic contrast of calm and fury',
  prophet_ant_hill: 'A kind figure in white robes carefully moving a small campfire away from a tiny ant hill in the golden desert, baby ants being carried to safety by worker ants, warm sunset, palm trees silhouetted',
  prophet_thirsty_dog: 'A compassionate woman in the desert removing her shoe to fill it with water from a deep well for a panting thirsty dog, warm sunset casting long shadows, palm trees, empathy in action',
  good_samaritan: 'A kind traveler kneeling on a dusty road to bandage the wounds of a fallen stranger, a patient donkey waiting nearby, warm sunset light over Biblical hills and olive trees, compassion to strangers',
  jesus_mustard_seed: 'A tiny glowing golden seed in an open palm magically growing into an enormous spreading tree with birds nesting in its branches, time-lapse transformation effect, warm magical light, wonder',
  buddha_elephant: 'A peaceful orange-robed monk standing perfectly still as a massive decorated elephant bows its great head gently before him, ancient Indian city gates in background, golden afternoon light, serenity',
  buddha_rice_bowl: 'A young village girl in a simple dress offering a golden bowl of rice to a thin peaceful man meditating under an enormous bodhi tree, morning mist, lotus flowers in a pond nearby, gentle reverence',
  jain_true_wealth: 'A wealthy merchant in silk robes humbly removing his ornate turban and placing it at the feet of a simple smiling monk sitting under a spreading tree, golden light, transformation from pride to peace',
  jain_spider_web: 'A delicate spider spinning a magnificent glowing web across a dark cave entrance, each strand catching moonlight like silver threads, a wide-eyed king watching in wonder from inside the cave, patience',
  jewish_one_good_deed: 'A young boy at a wooden table carefully piecing together a torn world map, each connected piece glowing with warm light, cozy study room with candles and old books, discovery and repair',
  jewish_two_pockets: 'A wise old rabbi with twinkling eyes and a kind smile holding two small glowing pieces of paper, one in each weathered hand, starry night sky visible through a window, candlelight on his face',
  sikh_langar: 'A young Sikh boy in a small turban proudly serving golden dal from a large pot to people of all backgrounds sitting cross-legged together on the floor, warm steam rising, Golden Temple kitchen glow',
  universal_lighthouse_keeper: 'A tiny white lighthouse on a rocky island at night, its golden beam cutting through wild storm clouds and crashing waves, a small boat in the distance following the light to safety, dramatic',
  universal_garden_of_mistakes: 'A magical garden where bright orange flowers instantly bloom wherever a young girl steps on the soil, each footprint becoming a flower, enchanted garden at golden sunset, wonder and growth',
  universal_invisible_boy: 'A lonely illustrated boy sitting on a park bench in the rain, wrapping his own jacket around a small shivering stray puppy, warm lamppost light creating a golden circle around them, compassion',
  universal_patience_river: 'A tiny silver stream of water patiently carving through a massive red cliff face over centuries, creating a stunning canyon, golden sunlight streaming through the narrow gap, persistence rewarded',
  universal_sharing_blanket: 'An elderly woman by a small fire in a snowy mountain village tearing her starry blue blanket in half to share with a shivering young traveler, snowflakes falling, warmth despite the cold',
  universal_respect_old_tree: 'A small girl hugging an enormous ancient oak tree in a village square, birds nesting in its massive branches, dappled golden sunlight through leaves, community of people gathered around, respect',
  universal_forgiveness_kite: 'A boy on a hilltop opening his hand to release a colorful kite string, the kite soaring free into a magnificent orange and purple sunset sky, feeling of release and peace, letting go',
  universal_wisdom_two_wolves: 'A grandmother and grandchild sitting by a glowing stone fireplace, two translucent wolf spirits — one golden, one shadow — facing each other in the flames above, wisdom being passed down',
  universal_humility_mountain: 'A proud snow-capped mountain looking down at a small green hill completely covered in wildflowers and playing children, clouds between them, contrast between cold grandeur and warm joy, humility',
  universal_bravery_first_step: 'A small girl in pajamas taking her first brave step down dark wooden stairs, holding the bannister tightly, a tiny warm golden candle glow visible at the bottom, courage in the dark',
  mothers_day_toronto: 'A child joyfully handing a bright yellow tulip to their smiling mother on a sunny bench by Toronto waterfront, CN Tower in soft background, cherry blossoms, spring sunshine, heartwarming love',

  // ══════ COLLECTION STORIES ══════
  col_loyal_dog: 'A golden retriever sitting patiently at a school gate in autumn, fallen leaves around, looking down the empty road waiting, warm afternoon light, loyalty and devotion, children\'s book style',
  col_lost_kitten: 'A tiny orange kitten shivering behind a grocery store in the rain, a kind girl\'s hand reaching down with a warm lunch box, puddle reflections, compassion, soft watercolor style',
  col_brave_rabbit: 'A small white rabbit running bravely through dark moonlit woods carrying a tiny baby bunny by the scruff, a fox shadow in the background, courage despite fear, soft dramatic lighting',
  col_parrot_truth: 'A bright green parrot on a perch in a colorful Indian market stall surrounded by mangoes, the parrot squawking honestly while the shopkeeper looks surprised, funny and warm scene',
  col_elephant_memory: 'A young elephant walking through misty green hills, following a memory of a small bird friend, birdsong notes visible as golden sparkles leading the way, determination and love',
  col_turtle_shell: 'A friendly old turtle with a cozy shell sheltering a tiny mouse, a ladybug, and a caterpillar from a dramatic rainstorm, warm light inside the shell, generosity despite discomfort',
  col_fire_truck: 'A shiny red fire truck with a nervous face approaching a building with orange flames, the truck trembling but moving forward, other trucks cheering from behind, courage despite fear',
  col_bicycle_race: 'A rusty old bicycle with a happy face carrying groceries and a child to school, while shiny racing bikes watch from a showroom, value through service not speed, warm neighborhood scene',
  col_train_patience: 'A sleek express train stopped on mountain tracks, waiting patiently for a stubborn cow on the rails, beautiful mountain scenery, sunset, patience versus speed, humorous and gentle',
  col_ambulance: 'A white ambulance with a kind face radioing for help at night, a fire truck and police car rushing to assist in different directions, teamwork in the city, warm emergency lights',
  col_rocket_dream: 'A shiny rocket on a launch pad trembling nervously, looking up at the enormous starry sky, a small girl whispering encouragement to it, overcoming fear of the unknown, dreamy night scene',
  col_school_bus: 'A cheerful yellow school bus driving over a bump, lunch boxes and kids bouncing and laughing inside, friendships being made through shared chaos, warm morning light, joyful community',
  col_invisible_hero: 'A translucent invisible girl quietly sitting next to a lonely boy at a school lunch table, her presence making him smile without knowing why, warm cafeteria light, gentle heroism',
  col_kindness_cape: 'A young Indian boy with golden threads weaving into a glowing cape behind him as he shares his lunch with a classmate, each kind act adding a thread, warm school playground',
  col_truth_shield: 'A young superhero holding a glowing blue shield that pulses brighter with each truth spoken, standing firm in front of friends, the shield radiating protective light, integrity',
  col_patience_power: 'The slowest superhero sitting calmly while chaos swirls around — other heroes rushing and crashing — waiting for the perfect moment, zen-like patience in costume, humorous contrast',
  col_empathy_girl: 'A girl with visible golden waves connecting her heart to the hearts of everyone around her — each person\'s emotion shown as a soft color aura, empathy as a visible superpower',
  col_forgiveness_hero: 'A female superhero dissolving heavy iron chains thrown at her by touching them, each chain turning into golden butterflies and flying away, forgiveness as power, dramatic transformation',
  col_lion_vs_eagle: 'A majestic lion and a proud eagle facing each other respectfully on a cliff edge between land and sky, neither fighting — just acknowledging each other\'s kingdom, mutual respect',
  col_ant_vs_elephant: 'A tiny determined ant carrying a leaf ten times its size walking past a massive elephant who watches in amazement, size versus strength, humorous scale comparison, warm savanna',
  col_tortoise_vs_hare: 'A hare stopped mid-race to help a baby fox caught in thorns, while the tortoise walks past toward the finish line, choosing kindness over winning, forest racing path',
  col_sun_vs_wind: 'A warm smiling sun gently shining on a traveler who removes his coat happily, while a frustrated wind blows clouds angrily in the background, gentleness versus force, dramatic sky',
  col_brain_vs_muscle: 'A thoughtful figure with a glowing brain building a lever next to a muscular figure pushing a boulder, both needed to solve the problem, teamwork of mind and body, warm village',
  col_ocean_vs_mountain: 'A vast blue ocean and a towering snow mountain facing each other with a small river connecting them, showing their interdependence, epic landscape, golden hour, harmony in nature',
  col_cricket_team: 'Eleven diverse kids standing proudly on a rocky field they cleared by hand over months, holding homemade cricket bats, their first pitch visible behind them, dawn light, determination',
  col_swimmer: 'A small determined girl swimming against a visible current in a pool, water splashing dramatically, other swimmers watching, third-place ribbon waiting at the end, persistence and grit',
  col_soccer_share: 'A boy mid-kick choosing to pass the soccer ball to a wide-open surprised teammate instead of shooting at an empty goal, stadium lights, selfless teamwork moment, freeze-frame action',
  col_fair_play: 'Two boys crossing a running race finish line together — one helping the other who fell — the crowd standing in the background giving a standing ovation, sportsmanship, golden afternoon',
  col_basketball_short: 'The shortest kid on a basketball team dribbling lightning-fast between tall players, passing the ball perfectly to a teammate for a score, speed as strength, dynamic court scene',
  col_marathon: 'A woman running alone on a long empty road at sunset, thirty strangers gradually joining to run alongside her, the last runner finishing together, community and persistence, dramatic light',
  col_grandpa_wisdom: 'An elderly grandfather in a small balcony garden with three pots and a plastic chair, a grandchild listening intently, city skyline behind, golden evening light, wisdom passing between generations',
  col_new_sibling: 'A young child tentatively holding a tiny baby\'s hand for the first time, the baby gripping one finger, both looking at each other with wonder, soft nursery light, new bond forming',
  col_moms_hands: 'A close-up of a mother\'s weathered hands — cooking, bandaging a knee, holding a small hand, buttoning a coat — in a soft montage style, warm golden light, love through action',
  col_dads_promise: 'A father in office clothes running through city streets at dusk, tie flying behind him, rushing to keep a promise to be at his child\'s school play, determination and love, urban scene',
  col_grandma_stories: 'An elderly Indian grandmother on a video call screen, her warm crinkly eyes filling the phone display while a child in Canada presses the phone to their ear, bridge between worlds, love across distance',
  col_family_meal: 'A whole family crowded in a small kitchen making biryani together — everyone bumping elbows, stirring pots, laughing — steam and warm spice colors filling the air, forgiveness through togetherness',
  col_moon_lonely: 'A luminous full moon looking down at Earth through wispy clouds, billions of tiny warm window lights visible on the planet below, the moon realizing it is watched and loved, cosmic loneliness healed',
  col_mars_red: 'A brave red planet standing alone facing an intense sun while other planets hide behind Jupiter, the surface transforming from blue to red, courage and transformation, dramatic space scene',
  col_saturn_rings: 'A lonely ringed planet welcoming broken pieces of a comet into its orbit, the fragments becoming beautiful glittering rings, generosity creating beauty, deep space with stars, warm palette',
  col_pluto_small: 'A tiny blue planet at the dark edge of the solar system with an enormous heart-shaped glacier visible on its surface, a NASA spacecraft approaching, smallness with big heart, touching',
  col_earth_gift: 'Planet Earth at the center of a circle of other planets, showing its blue oceans, green forests, and tiny visible lights of cities, the only planet with life, special and fragile, cosmic view',
  col_shooting_star: 'A small rock burning brilliantly as it falls through Earth\'s atmosphere, leaving a golden trail across the night sky, a child below making a wish, beauty in struggle, hope in the dark',
  col_japan_cherry: 'A small Japanese girl sitting peacefully under a blooming cherry blossom tree, pink petals falling like snow around her, Mount Fuji barely visible in the misty background, transient beauty',
  col_canada_maple: 'A bright red maple leaf on a Canadian flag gently being placed by First Nations and settler hands together, golden maple syrup dripping warmly, sharing as nation-building, autumn forest',
  col_india_river: 'Two children on opposite sides of a dry riverbed in Rajasthan, leaving small gifts for each other — a painted stone, a paper bird — connection across distance, warm desert sunset',
  col_egypt_pyramid: 'A tiny humble pyramid beside the enormous Great Pyramid of Giza, the small one with an open door glowing with warm light inside, size versus soul, dramatic desert sunset, humility',
  col_brazil_rainforest: 'An enormous ancient tree in the Amazon whose roots glow blue as they pull water from underground and release it as mist that becomes rain clouds above, the cycle of giving, magical realism',
  col_toronto_cn: 'The CN Tower soaring above Toronto skyline next to a tiny old brick house with warm light in its windows, tall versus old, new versus historic, Lake Ontario reflecting both, evening glow',

  // ══════ SERIES — DR. SPOCK SAYS ══════
  dsp_ep1_development: 'A warm kindly silver-haired doctor in a white coat sitting in a cozy living room armchair talking gently to a young parent, a preschool child playing with colorful blocks on the floor between them, soft lamp light, bookshelves with parenting books, warm golden atmosphere, trust and reassurance',
  dsp_ep2_ailments: 'A gentle doctor kneeling beside a cozy bed where a small child with a runny nose is tucked under a warm blanket, a cup of soup on the nightstand, soft tissues nearby, warm bedside lamp glowing amber, caring parent watching from doorway, comforting scene',
  dsp_ep3_firstaid: 'A kind doctor showing a parent how to put a bandage on a small child\'s scraped knee, the child sitting on a kitchen counter looking brave with a few tears, a small first aid kit open beside them, sunny kitchen with warm light, courage and care',
  dsp_ep4_behavior: 'A small child mid-tantrum on the floor of a cozy living room while a calm parent sits nearby at eye level with open arms, a kindly doctor figure observing with a gentle smile from an armchair, warm evening light, patience and love, soft watercolor style',
  dsp_ep5_special: 'A diverse group of children playing together in a sunny inclusive playground — one child in a small wheelchair, another with hearing aids, all laughing together, a gentle doctor figure watching proudly from a park bench, rainbow of abilities, warm golden light, joy and belonging',

  // ══════ SERIES — FIRE TRUCK ACADEMY ══════
  fta_ep1_afraid: 'A shiny red fire truck with trembling headlights racing alone through dark city streets at 3 AM toward a house with orange flames, a small girl clutching a stuffed bear visible in a second-floor window, sirens blazing blue and red against the night sky, fear turning into courage',
  fta_ep2_rescue: 'A bright red fire truck gently lowering a thin suction hose into a narrow storm drain on a rainy street, a tiny soaking wet orange kitten popping out of the hose into daylight, a crowd of cheering children with umbrellas, warm puddle reflections',
  fta_ep3_teamwork: 'Three fire trucks working in perfect formation at a school fire drill — one blasting a side window, one extending a ladder to the second floor, one positioned at the north side catching dummy children, all moving as one synchronized team, dramatic dawn light',
  fta_ep4_false_alarm: 'Four fire trucks parked outside a quiet shopping mall in bright noon sunlight, no smoke or flames anywhere, the trucks looking confused and deflated, a prankster kid peeking from behind a fire alarm pull handle, wasted sirens still echoing, frustration and lesson',
  fta_ep5_graduation: 'Four gleaming fire trucks lined up in a decorated fire station with streamers and bunting, a large chrome command truck pinning a small gold star above the headlights of a proud red engine, golden afternoon light streaming through the station bay doors, graduation ceremony',

  // ══════ SERIES — PANCHATANTRA TALES ══════
  pt_ep1_monkey: 'A clever brown monkey leaping from a crocodile\'s back onto a tall mango tree branch overhanging a silver river, the crocodile looking up with a foolish confused expression, ripe golden mangoes hanging from branches, warm tropical afternoon light through jungle canopy',
  pt_ep2_crow: 'A determined glossy black crow carefully dropping a smooth grey pebble into a tall clay pitcher in a dusty village courtyard, the water level inside visibly rising, a pile of small pebbles at the crow\'s feet, golden afternoon light, patience and persistence',
  pt_ep3_tortoise: 'A small green tortoise falling through the air above a patchwork of fields and villages after opening his mouth mid-flight, two geese flying above still holding a wooden stick between their beaks, the stick empty where the tortoise bit, dramatic sky, a haystack below',

  // ══════ SERIES — LIGHTNING WHEELS ══════
  lw_ep1_fastest: 'A shiny red race car with gold stripes stopped on a hill pushing a tiny struggling tricycle up the slope, flowers and sunset visible along the roadside, the race car looking genuinely happy for the first time, warm evening light, kindness over speed',
  lw_ep2_flat_tire: 'A tiny tricycle pedaling furiously down a neighbourhood street carrying a brand-new tire on its back, racing toward a deflated red race car with a flat front tire at a starting line, clocks showing urgency, warm morning light, the smallest friend saving the day',
  lw_ep3_last_race: 'A red race car screeching to a halt inches from a small puppy sitting in the middle of a race track, a shinier blue car zooming past toward a finish line in the background, the puppy safe on the red car\'s hood, crowd standing in ovation, golden sunset',

  // ══════ SERIES — ROCKET ADVENTURES (OLD) ══════
  ra_ep1_heights: 'A gleaming silver rocket trembling on a launchpad under a starry sky, a small girl at the fence below whispering encouragement, the rocket\'s engines just beginning to glow blue, clouds parting above revealing infinite stars, the moment before liftoff, courage',
  ra_ep2_moon: 'A shiny rocket sitting on grey lunar dust beside a small dusty rover with cracked solar panels, a spare battery glowing between them, Earth hanging as a tiny blue marble in the black sky above, two lonely machines becoming friends on the silent Moon',
  ra_ep3_home: 'A rocket and a small rover floating together through black space with no engine fire, drifting slowly toward a growing blue Earth, an orange heat shield beginning to glow, a parachute packed and ready, coming home slow and together, dramatic starfield',

  // ══════ SERIES — KINDNESS SQUAD ══════
  ks_ep1_cape: 'A young Indian boy on a school playground with glowing golden threads weaving themselves into a small cape on his back as he shares his sandwich with a classmate, each thread representing a kind act, warm school-day sunlight, magical realism',
  ks_ep2_feel: 'A girl with visible golden waves of empathy radiating from her chest sitting silently next to a lonely new student surrounded by a heavy grey fog, the golden waves slowly dissolving the grey, empty school cafeteria, warm afternoon light filtering through windows',
  ks_ep3_shield: 'A boy holding a blazing bright blue shield that pulses with white light, standing protectively in a school hallway, a bully stumbling backward blinded by the glow, a golden-caped boy and an empathy-glowing girl flanking him, The Kindness Squad united, dramatic corridor light',

  // ══════ SERIES — PLANET EXPLORERS ══════
  pe_ep1_moon: 'A luminous full moon with a gentle face looking down through wispy clouds at billions of tiny warm window lights on Earth below, the Sun whispering from the edge of the frame, the Moon realizing children look up at her every night, cosmic warmth and connection',
  pe_ep2_mars: 'A brave red planet standing alone facing a fierce blazing sun while other planets hide behind Jupiter in the background, the red surface cracked and scarred but standing tall, solar wind visibly stripping the atmosphere, courage and transformation in deep space',
  pe_ep3_pluto: 'A tiny blue planet at the dark edge of the solar system with an enormous heart-shaped white glacier glowing on its surface, a small NASA spacecraft approaching with camera flashing, the other planets watching in awe from far away, smallness with enormous heart',

  // ══════ SERIES — RAINBOW KINDERGARTEN ══════
  rk_ep1_canoe: 'Twenty small children with backpacks holding a buddy rope walking through Canoe Landing Park in Toronto hunting for shapes, one child pointing excitedly at a hexagonal bolt, the CN Tower rising in the soft background, sunny community walk, warm school-day light',
  rk_ep2_concert: 'Twenty kindergarten children wearing hand-painted Earth globe hats standing on a school stage with arms wide open singing, parents in the audience crying and standing, one hat crooked over a child\'s eyes, warm gym lights, pure joy and imperfection',
  rk_ep3_brickworks: 'A wide-eyed kindergartner reaching out one finger to gently touch the smooth dark green shell of a Midland Painted Turtle in a conservatory at Evergreen Brick Works, yellow and red markings visible on the shell, the turtle blinking slowly, wonder and gentleness',

  // ══════ SERIES — LITTLE ASTRONAUT ══════
  la_ep1_launch: 'A small child in a white-and-blue space suit climbing a metal ladder toward a silver rocket on a launchpad under a pre-dawn starry sky, a green GO button glowing inside the cockpit window above, the moment before the first adventure, courage and wonder',
  la_ep2_moon: 'A tiny astronaut sitting alone on a grey Moon rock with eyes closed, grey dust and craters stretching to the horizon, Earth as a small blue marble in the black sky, absolute silence, the child learning patience from four billion years of stillness',
  la_ep3_mars: 'A child astronaut kneeling in a clear greenhouse dome on the red Martian surface, carefully watering five small pots with a tiny watering can, one pot sprouting a mysterious golden-flowered tree, dim reddish Martian sunlight filtering through, wonder and nurture',
  la_ep4_saturn: 'A small rocket weaving gracefully between enormous chunks of glittering ice in Saturn\'s rings, the golden planet massive below, ice crystals catching starlight in silver and blue, the child astronaut visible through the cockpit window with wide eyes, cosmic beauty',
  la_ep5_home: 'A tiny astronaut standing on a rescue boat in the ocean looking up at the sky, the rocket bobbing nearby with parachute still draped, warm salty air and crying seabirds, Earth\'s blue sky enormous overhead after weeks in space, gratitude and homecoming',

  // ══════ SERIES — WHO WOULD WIN? ══════
  www_ep1_lion_eagle: 'A majestic golden-maned lion and a fierce eagle with six-foot wingspan standing respectfully facing each other on a cliff edge, a forest clearing full of watching animals below, Professor Puzzle with enormous spectacles at a chalkboard writing TEAMWORK, warm sunset',
  www_ep2_ant_elephant: 'A tiny determined ant standing on a microphone speaking to a stunned enormous elephant in a forest clearing, thousands of ants visible sealing a dam crack in the background, Professor Puzzle writing on his chalkboard, dramatic scale contrast, warm savanna light',
  www_ep3_sun_wind: 'A warm smiling golden sun gently shining down on a happy traveller removing his coat on a dusty road, while a frustrated grey wind blows angrily in the dark clouds above, Professor Puzzle watching from the clearing, gentleness defeating force, dramatic sky contrast',
  www_ep4_brain_muscle: 'A small grey owl perched atop a boulder that has split cleanly in two from ice in a crack, a massive gorilla sitting exhausted beside it staring in amazement, water still frozen in the crack, forest village path now open, Professor Puzzle writing on chalkboard, dawn light',
  www_ep5_ocean_mountain: 'A vast blue ocean and a towering snow-capped mountain facing each other with a small silver river connecting them, clouds carrying rain from ocean to mountain peak, Professor Puzzle standing small between them with a final chalkboard reading NOBODY, golden hour, harmony',

  // ══════ SERIES — CAMPING & OUTDOORS ══════
  co_ep1_setup: 'A family of three struggling to set up a lopsided tent in a pine forest clearing beside a still lake at sunset, poles going the wrong way, a child giggling while holding a pole, warm orange sky reflected in the mirror-like lake, imperfect and wonderful',
  co_ep2_night_sounds: 'A child lying wide-eyed in a sleeping bag inside a tent at night, an owl silhouetted on a branch outside visible through the tent fabric, moonlight filtering through trees, a loon calling across a dark lake, the forest alive with gentle mysterious sounds',
  co_ep3_river: 'A child mid-crossing in a rushing shallow river using a walking stick for balance, water splashing around their shins, slippery round stones visible underwater, parents on either bank reaching out, a hidden waterfall visible through trees on the far side, adventure and bravery',
  co_ep4_campfire: 'A family of three sitting on logs around a glowing campfire at night, orange sparks flying upward like fireflies into a star-filled sky, marshmallows on sticks, the child mid-story with animated hands, golden firelight on their faces, no phones anywhere',
  co_ep5_sunrise: 'Three small silhouetted figures standing on a rocky mountain summit at dawn, a spectacular orange and pink sunrise exploding across the horizon, the valley below with a tiny lopsided tent visible by a silver lake, hot chocolate cups steaming in their hands, gratitude',

  // ══════ SERIES — MUSIC LESSONS ══════
  ml_ep1_drum: 'A big red drum with brass edges playing alone in an empty music room, all other instruments silent in their cases, the drum looking confused and lonely, scattered sheet music on the floor, warm afternoon light through dusty windows, the cost of being too loud',
  ml_ep2_violin: 'A shy violin on a concert hall stage under a single spotlight, bow raised trembling before the first note of a solo, an entire orchestra sitting still and silent behind, a packed audience in shadow, the moment between fear and beauty, dramatic warm stage light',
  ml_ep3_piano: 'A piano keyboard seen from above with the black keys and white keys glowing different colours, an old woman\'s gentle hands bringing them together into a single chord, musical notes floating upward as golden light, harmony from difference, warm music room atmosphere',
  ml_ep4_singing: 'A tiny ukulele standing on a stool at the front of a music room singing with a small wobbly voice, a large trumpet and guitar watching in surprise from behind, old Cello crying a single low trembling note in the corner, honest simplicity winning over flashiness',
  ml_ep5_orchestra: 'An orchestra of illustrated instruments playing together in a children\'s hospital ward, a girl in a hospital bed smiling for the first time in days, warm golden sound waves visible in the air, IV stands and rainbow murals on walls, music as medicine, tender scene',

  // ══════ SERIES — WATER & SWIM ══════
  ws_ep1_splash: 'A small girl in a swimsuit standing at the edge of an enormous blue swimming pool, toes curled over the tiles, one toe tentatively dipping into the water, a kind swim coach sitting on the pool edge nearby with feet dangling in, warm community centre light, first step',
  ws_ep2_float: 'A girl floating on her back in a swimming pool with eyes closed and arms spread, the water holding her like a gentle hand, ceiling lights looking like blurry stars from underwater perspective, a peaceful expression replacing fear, warm aqua light, trust and surrender',
  ws_ep3_deep: 'A girl treading water in the dark deep end of a swimming pool, looking down into blue emptiness where the floor disappears, the red-and-white rope divider behind her, a coach swimming beside her, the moment of realizing she doesn\'t need the ground, blue-lit courage',
  ws_ep4_fish: 'A girl swimming in a sun-dappled green lake surrounded by a school of golden sunfish, their scales flashing in filtered sunlight, pine trees reflected in the water, a natural lakeshore with pebbles visible below, swimming with nature, magical and real',
  ws_ep5_lifeguard: 'An older girl sitting on the pool edge with feet in the water next to a scared new girl in a pink swimsuit with curled toes, the older girl offering her hand with a knowing smile, the pool stretching behind them, passing on courage, warm community centre glow',

  // ══════ SERIES — MATHS ADVENTURES ══════
  ma_ep1_garden: 'A boy standing amazed inside a magical garden where flowers grow in numbered rows — one giant sunflower, two red roses, three purple tulips — a cheerful ladybird with five spots on a leaf nearby, a green gate behind him, warm golden light, numbers everywhere in nature',
  ma_ep2_detective: 'A girl detective with a magnifying glass examining hexagonal stickers on a school hallway floor leading toward a playground, a notebook full of shape drawings in her other hand, twelve missing squares arranged in a grid visible in a sandbox through the window, mystery and maths',
  ma_ep3_pattern: 'Two children in a dusty library basement staring at a glowing brass-and-copper machine with gears and levers, the green screen displaying 2-4-6-8-?, golden marbles rolling out of a small drawer, warm mechanical glow, patterns as the language of the universe',
  ma_ep4_feast: 'A young girl carefully cutting a round cake into eight perfect equal slices at a crowded family dinner table, eight people waiting with plates, a rectangular pizza and bowl of strawberries also on the table, warm family kitchen light, fractions as fairness and love',
  ma_ep5_measure: 'A boy and his father measuring the shadow of an enormous oak tree in a sunny garden, the boy holding a tape measure along the tree\'s long shadow, rulers laid end-to-end nearby, a small snail trail being measured with a ruler, golden afternoon light, measuring the world',

  // ══════ SERIES — PLANETS & STARS ══════
  ps_ep1_moon: 'A silver Moon floating near the Sun, catching blazing light and reflecting it softly downward onto sleeping children visible through tiny windows on Earth below, the Moon glowing with pride, gentle silver moonbeams cutting through night clouds, sharing borrowed light',
  ps_ep2_mars: 'A cracked red planet with enormous Olympus Mons mountain and the vast Valles Marineris canyon scar visible, standing alone against a fierce solar wind with no atmosphere, other planets in the far background, scars worn like medals, courage and survival in deep space',
  ps_ep3_jupiter: 'An enormous orange-and-white striped planet with a shrinking Great Red Spot storm, tiny moons orbiting peacefully around it, Saturn floating nearby with golden rings offering gentle advice, the storm visibly smaller than before, patience and letting go, warm space palette',
  ps_ep4_saturn: 'A golden planet surrounded by billions of glittering ice and rock fragments forming magnificent rings, a small lonely asteroid drifting in to join the orbit, other broken comet pieces already circling peacefully, deep space background, generosity creating beauty from broken pieces',
  ps_ep5_pluto: 'A tiny blue-grey planet at the very edge of a dark solar system with a massive heart-shaped white glacier glowing on its surface, a small spacecraft named New Horizons flying close with cameras flashing, the other planets watching from billions of miles away, vindication and love',

  // ══════ SERIES — GEOMETRY & SHAPES ══════
  gs_ep1_circle: 'A smooth yellow circle rolling through Shapeville past streetlights casting circular pools of light, a full moon circle overhead, round clock tower in the background, all the cornered shapes watching from doorways, the circle realizing she is everywhere, warm night glow',
  gs_ep2_triangle: 'A small orange triangle bracing herself underneath a sagging library shelf full of heavy books, her three corners pressing perfectly into wall, shelf, and bookend, the shelf steady again, larger shapes watching in admiration, warm school library light, strength from three sides',
  gs_ep3_square: 'A blue square standing in front of an enormous mosaic mural made of thousands of tiny colourful square tiles forming a sunset over water, the square realizing he is the building block of all visible art, warm community centre wall, ordinariness becoming extraordinary',
  gs_ep4_hexagon: 'A peaceful purple hexagon standing beside a golden beehive on an apple tree branch, the honeycomb visible inside showing thousands of perfect hexagonal cells filled with golden honey, bees buzzing around, warm orchard light, nature\'s perfect patient geometry',
  gs_ep5_city: 'All the shapes of Shapeville working together to build a community centre — triangles forming the roof, squares making walls, circles as windows catching light, hexagons tiling the floor in blue and gold, beautiful open space inside, warm golden construction-day light, unity',

  // ══════ SERIES — ROCKET ADVENTURES (TEAM) ══════
  rat_ep1_build: 'Five diverse kids in a garage building a seven-foot silver-and-red rocket named HOPE-1, one welding fins, one drawing blueprints, one calculating on paper, one mapping stars, the smallest one asking a question, tools and parts scattered everywhere, warm garage workshop light',
  rat_ep2_launch: 'A silver-and-red homemade rocket lifting off from a makeshift launchpad of cinder blocks behind a school, a column of white smoke exploding from the base, five kids and a crowd watching with open mouths, an orange parachute visible at the top, blue morning sky, liftoff moment',
  rat_ep3_asteroid: 'Five kid astronauts inside a spacecraft cockpit staring at a car-sized asteroid tumbling toward them through the window, one child pressing a cargo bay eject button, scientific equipment launching into the void toward the asteroid, tension and sacrifice, dramatic space lighting',
  rat_ep4_station: 'Five kid astronauts floating in the cupola window of the International Space Station with a Japanese commander, Earth glowing enormous and blue below them, solar panel wings visible outside, floating tortillas and equipment around them, wonder and weightlessness',
  rat_ep5_landing: 'A small child astronaut walking down a hill on an alien planet with blue-green grass toward a small shimmering alien figure holding a glowing orb, two moons in a purple sky, dome-shaped dwellings in a spiral valley behind, hands open in peace, first contact, golden alien sunset',
// ══════ WHO WOULD WIN — ANIMAL BATTLES ══════
  wwwa_ep1_lion_tiger: 'A majestic golden lion and a massive orange-striped tiger standing face to face on a dramatic savanna cliff edge at sunset, both roaring, golden dust swirling between them, muscles tensed, epic confrontation under a blood-orange sky',
  wwwa_ep2_scorpion_tarantula: 'A glowing ultraviolet scorpion with raised stinger facing a giant hairy tarantula in a moonlit desert arena, sand particles floating, dramatic shadows, both in fighting stance, tiny but terrifying close-up perspective',
  wwwa_ep3_cheetah_leopard: 'A sleek spotted cheetah mid-sprint blur racing alongside a muscular leopard perched powerfully on a tree branch, African grassland, golden hour, speed lines on cheetah, raw strength visible in leopard muscles',
  wwwa_ep4_shark_croc: 'A great white shark breaching upward from deep blue water toward a massive saltwater crocodile lunging from a muddy riverbank, water splashing dramatically at the collision point, tropical coastline background',
  wwwa_ep5_eagle_owl: 'A golden eagle with spread seven-foot wings diving through golden daylight on the left, and a great horned owl with glowing amber eyes emerging from a dark forest on the right, dawn/dusk dividing line between them',
  wwwa_ep6_gorilla_bear: 'A silverback gorilla beating its chest standing on a mossy rock facing a massive grizzly bear rearing up on hind legs, misty mountain forest, dramatic size comparison, raw power radiating from both creatures',
  wwwa_ep7_cobra_mongoose: 'A king cobra raised tall with hood spread wide and a tiny brave mongoose in a fighting crouch below it, Indian jungle clearing, dramatic size difference, the mongoose looking fearless despite being ten times smaller',
  wwwa_ep8_whale_squid: 'A sperm whale descending into pitch-black deep ocean encountering a giant squid with enormous dinner-plate eyes and reaching tentacles, bioluminescent particles floating, dramatic deep-sea darkness with whale sonar rings',
  wwwa_ep9_rhino_hippo: 'A charging rhinoceros with lowered horn about to collide with a hippo opening its massive jaws impossibly wide showing twenty-inch teeth, African waterhole at dusk, dust and water droplets frozen in the air',
  wwwa_ep10_wolf_hyena: 'A pack of grey wolves in formation on a snowy ridge facing a clan of spotted hyenas gathered on an African plain, split-screen effect with snow on left and savanna on right, both groups looking fierce and unified',

  // ══════ DISCOVER COUNTRIES — GEOGRAPHY SERIES ══════
dc_in_ep1_geo: 'Aerial view of India from space showing the Himalayan mountains at the top, the green Ganges plains, golden Thar desert on the left, and blue Indian Ocean below, with the Indian flag 🇮🇳 waving in the corner, warm golden hour light, children storybook map style',
dc_in_ep2_history: 'Ancient Indus Valley civilization scene with decorated buildings, the Taj Mahal in the distance, a Mughal emperor on an elephant, and Mahatma Gandhi walking peacefully, timeline flowing left to right, Indian flag colors woven through, storybook illustration',
dc_in_ep3_places: 'Split panel showing the Taj Mahal in moonlight, the Red Fort at sunset, the Golden Temple reflected in water, and the Gateway of India with Mumbai skyline, Indian flag draped across the top, warm watercolor',
dc_in_ep4_culture: 'Colorful Indian festival scene with Holi powder colors flying, plates of biryani and samosas, a cricket bat, Bollywood dancers, sari fabrics, and a tabla drum, Indian flag 🇮🇳 prominently displayed, joyful celebration',
dc_in_ep5_facts: 'Fun infographic-style illustration showing a tiger, a space rocket (ISRO), a chess board, a mango tree, Bollywood film strip, and the number 1.4 billion, all arranged around a large Indian flag, colorful and playful',
dc_ca_ep1_geo: 'Sweeping Canadian landscape showing Rocky Mountains with snow peaks, a red canoe on a turquoise lake, northern lights in the sky, maple trees in autumn orange, and the Canadian flag 🇨🇦 planted on a mountain peak, breathtaking nature',
dc_ca_ep2_history: 'Indigenous totem pole on the left, a voyageur canoe in the middle, the Parliament building in Ottawa on the right, with a timeline flowing through, maple leaves falling, Canadian flag waving, warm storybook style',
dc_ca_ep3_places: 'CN Tower in Toronto, Niagara Falls with rainbow, Parliament Hill with Peace Tower, a lighthouse on the Atlantic coast, mountains of Banff, all connected by a red maple leaf trail, Canadian flag prominent',
dc_ca_ep4_culture: 'Ice hockey players, a plate of poutine, a maple syrup bottle pouring onto pancakes, a Mountie on a horse, kids playing in snow, multicultural faces, Canadian flag 🇨🇦, cozy winter warmth',
dc_ca_ep5_facts: 'Playful illustration of a moose wearing a toque, world largest coastline shown as wavy blue line, a jar of maple syrup, hockey stick, two official language signs (EN/FR), all around a big Canadian flag, fun facts style',
dc_us_ep1_geo: 'Map-style aerial of the USA showing Grand Canyon in red, green forests of the east, golden California coast, snowy Rockies, Great Lakes in blue, and the Statue of Liberty, American flag waving, vibrant storybook',
dc_us_ep2_history: 'Timeline scene with Native American tepees, the Mayflower ship, the Liberty Bell, Abraham Lincoln, Martin Luther King Jr speaking, and a moon landing astronaut, American flag weaving through, warm historical illustration',
dc_us_ep3_places: 'Statue of Liberty, Golden Gate Bridge in fog, Mount Rushmore, the White House, Empire State Building, and Disneyland castle, all connected by Route 66 road, American flag bunting across the top',
dc_us_ep4_culture: 'Baseball game, a plate of burgers and apple pie, jazz musicians playing, Hollywood sign, NASA rocket, kids of many ethnicities doing a high-five, American flag 🇺🇸, diverse and energetic',
dc_us_ep5_facts: 'Fun illustration showing a bald eagle, the Moon with a flag on it, a basketball, a hot dog, the Grand Canyon depth comparison, and 50 tiny stars, all arranged playfully around American flag',
dc_gb_ep1_geo: 'Aerial view of the British Isles showing green rolling hills of England, Scottish Highlands with purple heather, Welsh mountains, white cliffs of Dover, and the River Thames, Union Jack flag in the corner, misty and magical',
dc_gb_ep2_history: 'Medieval castle with knights, a Viking ship, Queen Elizabeth I in a ruff collar, Big Ben and Parliament, and the Beatles crossing Abbey Road, Union Jack weaving through timeline, rich historical illustration',
dc_gb_ep3_places: 'Big Ben and Houses of Parliament, Tower Bridge, Buckingham Palace with guards, Stonehenge at sunset, Edinburgh Castle on a cliff, all under a rainy sky with a rainbow, Union Jack bunting',
dc_gb_ep4_culture: 'Afternoon tea set with scones, a red double-decker bus, a football (soccer) match, Harry Potter-style wizard hat, the Beatles, a corgi dog, fish and chips, all around a Union Jack flag, cozy British charm',
dc_gb_ep5_facts: 'Playful illustration of a corgi wearing a crown, Big Ben clock, a red phone box, 67 million cups of tea, the London Underground roundel, and a Shakespeare quill, arranged around Union Jack, fun facts style',
dc_jp_ep1_geo: 'Mount Fuji with cherry blossoms in foreground, bullet train passing through, Japanese islands visible from above, ocean on all sides, bamboo forest, and the Japanese flag 🇯🇵 with rising sun, serene and beautiful',
dc_jp_ep2_history: 'Samurai warrior, ancient wooden temple, geisha with parasol, the Emperor palace, Hiroshima peace crane, and modern Tokyo skyline, all flowing in a zen garden timeline, Japanese flag prominent, respectful illustration',
dc_jp_ep3_places: 'Mount Fuji reflected in a lake, Fushimi Inari red torii gates in a row, Himeji Castle in white, Tokyo Tower at night, a zen garden with raked sand, cherry blossom petals floating, Japanese flag',
dc_jp_ep4_culture: 'Sushi plate with chopsticks, a sumo wrestler, anime characters, a child in a kimono, origami cranes, a martial arts dojo, cherry blossom festival, Japanese flag 🇯🇵, colorful and respectful',
dc_jp_ep5_facts: 'Fun illustration showing a bullet train with speed lines, a vending machine with weird items, an earthquake-proof building flexing, a robot waving, 6,852 islands shown as dots, around Japanese flag, playful facts',
dc_cn_ep1_geo: 'Great Wall of China winding through misty green mountains, the Yangtze River flowing, Gobi Desert golden sands, terraced rice paddies, pandas in bamboo forest, Chinese flag 🇨🇳 on the wall, epic scale',
dc_cn_ep2_history: 'Terracotta warriors standing in rows, ancient silk road with camels, the Great Wall being built, Chinese dragon dancing, paper and compass being invented, Chinese flag weaving through, rich historical illustration',
dc_cn_ep3_places: 'The Great Wall stretching into distance, Forbidden City with red walls, Shanghai skyline with Oriental Pearl Tower, Terracotta Army, Li River with karst mountains, Chinese lanterns hanging, flag prominent',
dc_cn_ep4_culture: 'Dragon dance celebration, dim sum steamer baskets, a panda eating bamboo, Chinese calligraphy brush painting, kung fu poses, Chinese New Year fireworks, chopsticks, Chinese flag, festive and vibrant',
dc_cn_ep5_facts: 'Fun illustration of a panda doing kung fu, the Great Wall from space view, a plate of noodles being pulled extra long, a Chinese dragon, 1.4 billion people shown as tiny figures, around Chinese flag',
dc_au_ep1_geo: 'Uluru (Ayers Rock) glowing red at sunset, Great Barrier Reef with colorful coral underwater, Sydney harbour from above, vast golden outback, eucalyptus forests, Australian flag 🇦🇺, sun-drenched and vivid',
dc_au_ep2_history: 'Aboriginal dot painting art, a didgeridoo player, Captain Cook ship arriving, gold rush miners, modern Sydney Opera House, boomerang flying, Australian flag in timeline, respectful indigenous representation',
dc_au_ep3_places: 'Sydney Opera House with Harbour Bridge, Uluru at sunset, Great Barrier Reef snorkeling, Twelve Apostles sea stacks, a kangaroo hopping past the Melbourne skyline, Australian flag prominent',
dc_au_ep4_culture: 'Barbecue (barbie) with shrimp, a surfer riding a wave, a koala in a eucalyptus tree, AFL football, Vegemite jar, kids saying G day, boomerang, Australian flag 🇦🇺, sunny and friendly',
dc_au_ep5_facts: 'Playful illustration of a kangaroo boxing, a koala sleeping 22 hours, Great Barrier Reef visible from space, a spider (friendly-looking), a platypus, all arranged around Australian flag, fun facts',
dc_br_ep1_geo: 'Amazon rainforest canopy from above with a winding river, Rio skyline with Sugarloaf Mountain, Iguazu Falls thundering, golden beach with palm trees, Brazilian flag 🇧🇷, lush tropical colors',
dc_br_ep2_history: 'Indigenous Tupi people, Portuguese ships arriving, coffee plantations, Carnival origins, Christ the Redeemer being built, Pele playing football, Brazilian flag in timeline, vibrant illustration',
dc_br_ep3_places: 'Christ the Redeemer statue with arms wide on a misty mountain, Iguazu Falls rainbow, Amazon River from above, Copacabana Beach, Sao Paulo skyline, Brazilian flag prominent, breathtaking views',
dc_br_ep4_culture: 'Carnival dancers in colorful feathered costumes, a football being kicked, a plate of feijoada, samba musicians, capoeira martial dancers, a toucan, Brazilian flag 🇧🇷, pure joy and rhythm',
dc_br_ep5_facts: 'Fun illustration of a toucan wearing a Carnival headdress, the Amazon labeled as lungs of the earth, a coffee cup, a football with 5 World Cup stars, the longest beach, around Brazilian flag',
dc_fr_ep1_geo: 'Eiffel Tower with lavender fields of Provence below, French Alps with snow, Atlantic coast, the Seine River through Paris, vineyards, French flag 🇫🇷 flying from the tower top, romantic and beautiful',
dc_fr_ep2_history: 'Roman aqueduct, medieval knights, Joan of Arc with banner, the French Revolution with Bastille, Napoleon on horseback, and modern Eiffel Tower, French tricolor weaving through timeline',
dc_fr_ep3_places: 'Eiffel Tower sparkling at night, Palace of Versailles golden hall, Mont Saint-Michel on its island, Louvre Museum with glass pyramid, Notre-Dame Cathedral, French flag bunting, magical Paris lights',
dc_fr_ep4_culture: 'Croissants and baguettes, a chef with a tall hat, Tour de France cyclists, a mime artist, ballet dancers, stinky cheese wheel, a beret, French flag 🇫🇷, charming and artistic',
dc_fr_ep5_facts: 'Playful illustration of a French bulldog wearing a beret, the Eiffel Tower height comparison, a snail on a plate (escargot), 400 types of cheese, the Louvre as most visited museum, around French flag',
dc_eg_ep1_geo: 'Nile River flowing through golden desert with pyramids on one side, green fertile delta, Red Sea coral reef, Sahara sand dunes, Egyptian flag 🇪🇬 planted between the pyramids, ancient and majestic',
dc_eg_ep2_history: 'Pharaohs and pyramids being built, hieroglyphics on a wall, Cleopatra, the Sphinx watching over the desert, a papyrus scroll being written, Egyptian flag in timeline, golden and mysterious',
dc_eg_ep3_places: 'Great Pyramid of Giza with Sphinx in foreground, Valley of the Kings entrance, Abu Simbel temple with giant statues, Karnak Temple columns, felucca boat on the Nile, Egyptian flag prominent',
dc_eg_ep4_culture: 'Falafel and koshari plate, Arabic calligraphy, a belly dancer, Egyptian cotton, kids playing near the Nile, ancient and modern Cairo side by side, Egyptian flag 🇪🇬, warm and timeless',
dc_eg_ep5_facts: 'Fun illustration of a cat wearing a pharaoh headdress (cats were sacred), pyramids with alien question mark (playful), mummies, 365-day calendar invention, Nile as longest river, around Egyptian flag',
dc_mx_ep1_geo: 'Mexican landscape with volcanic peaks, turquoise Caribbean coast, Sonoran desert with cacti, jungle cenotes (sinkholes with blue water), Sierra Madre mountains, Mexican flag 🇲🇽 with eagle and snake',
dc_mx_ep2_history: 'Aztec pyramid of Tenochtitlan, Mayan calendar stone, Spanish conquistador ships, Day of the Dead origins, Mexican Revolution heroes, Mexican flag in timeline, colorful and proud',
dc_mx_ep3_places: 'Chichen Itza pyramid, Mexico City Zocalo, Cancun turquoise beach, Frida Kahlo blue house, Copper Canyon, cenote with swimmer, Mexican flag prominent, vibrant destinations',
dc_mx_ep4_culture: 'Tacos and guacamole feast, mariachi band playing, Dia de los Muertos sugar skulls and marigolds, lucha libre wrestler, piñata, a child in traditional dress, Mexican flag 🇲🇽, festive and colorful',
dc_mx_ep5_facts: 'Playful illustration of an axolotl smiling, chocolate being invented by Aztecs, the worlds smallest volcano, a chihuahua, 69 languages spoken, all arranged around Mexican flag, fun facts style',
dc_it_ep1_geo: 'Italy boot shape visible from above, blue Mediterranean Sea, snow-capped Alps at top, rolling Tuscan hills with cypress trees, volcanic Vesuvius, Amalfi Coast, Italian flag 🇮🇹 tricolor, bella Italia',
dc_it_ep2_history: 'Roman Colosseum with gladiators, Leonardo da Vinci sketching, Roman aqueduct, Renaissance Florence, Galileo with telescope, Italian flag in timeline, golden classical illustration',
dc_it_ep3_places: 'Colosseum in Rome, Leaning Tower of Pisa, Venice gondola on canal, Florence Duomo dome, Pompeii ruins with Vesuvius behind, Italian flag bunting, architectural wonders',
dc_it_ep4_culture: 'Pizza being tossed, pasta varieties, a Vespa scooter, opera singer, kids playing calcio (football), gelato cone, a vineyard, Italian flag 🇮🇹, la dolce vita feeling',
dc_it_ep5_facts: 'Fun illustration of a pizza as a clock face, the Leaning Tower actually leaning, a tiny Vatican City, 350 types of pasta shapes, a Ferrari, all around Italian flag, playful facts',
dc_de_ep1_geo: 'Bavarian Alps with castle Neuschwanstein, Black Forest dark pine trees, Rhine River valley with castles, North Sea coast, rolling farmland, German flag 🇩🇪 black-red-gold, fairy tale landscape',
dc_de_ep2_history: 'Medieval castle, Gutenberg printing press, Brandenburg Gate, Berlin Wall being painted with art, a VW Beetle, German flag in timeline, invention and reunification theme',
dc_de_ep3_places: 'Neuschwanstein Castle (Disney inspiration), Brandenburg Gate, Cologne Cathedral, Black Forest cuckoo clock village, Berlin TV Tower, German flag prominent, fairy tale settings',
dc_de_ep4_culture: 'Pretzel and bratwurst, Oktoberfest celebration, a soccer ball, gummy bears, Christmas market with lights, a cuckoo clock, German flag 🇩🇪, warm and festive',
dc_de_ep5_facts: 'Playful illustration of a gummy bear (invented in Germany), Autobahn with no speed limit, 1500 types of sausage, Christmas tree tradition origin, Berlin Zoo, around German flag',
dc_kr_ep1_geo: 'Korean peninsula from above showing green mountains, Seoul cityscape, Jeju Island volcanic coast, cherry blossom roads, DMZ border, Korean flag 🇰🇷 taegukgi, dynamic landscape',
dc_kr_ep2_history: 'Ancient Joseon dynasty palace, Korean turtle ship, Hangul alphabet being created, traditional hanbok dress, modern K-pop stage, Korean flag in timeline, tradition meets innovation',
dc_kr_ep3_places: 'Gyeongbokgung Palace, N Seoul Tower at night, Jeju Island stone grandpa statues, Bukchon Hanok Village traditional houses, Lotte World Tower, Korean flag prominent, stunning contrast old-new',
dc_kr_ep4_culture: 'Bibimbap in stone bowl, K-pop idols performing, taekwondo kick, hanbok traditional dress, kimchi jars, PC gaming setup, Korean BBQ grill, Korean flag 🇰🇷, trendy and traditional',
dc_kr_ep5_facts: 'Fun illustration showing a K-pop microphone, worlds fastest internet wifi symbol, kimchi jar with 200 varieties, Gangnam Style dance pose, Korean age system explanation, around Korean flag',
dc_ru_ep1_geo: 'Vast Russian landscape from Siberian snow forests to Moscow, Lake Baikal deep blue, Ural Mountains dividing Europe-Asia, Trans-Siberian Railway, Russian flag 🇷🇺, epic scale and snow',
dc_ru_ep2_history: 'Kremlin and Red Square, a cosmonaut in space (Gagarin), matryoshka dolls, Peter the Great building St Petersburg, Faberge egg, Russian flag in timeline, grand and ambitious',
dc_ru_ep3_places: 'St Basils Cathedral colorful onion domes, Hermitage Museum, Kremlin walls, Trans-Siberian train in snowy forest, Lake Baikal frozen blue, Russian flag prominent, fairy tale architecture',
dc_ru_ep4_culture: 'Ballet dancer in Swan Lake, a samovar tea set, borscht soup, matryoshka nesting dolls, chess pieces, ice hockey, Russian flag 🇷🇺, elegant and artistic',
dc_ru_ep5_facts: 'Fun illustration of a bear (friendly) in a space helmet, Lake Baikal depth comparison, 11 time zones shown as clocks, matryoshka dolls nesting, worlds largest country outline, around Russian flag',
dc_za_ep1_geo: 'Table Mountain with Cape Town below, Kruger Park savanna with Big Five animals, Drakensberg Mountains, coastline where two oceans meet, vineyards, South African flag 🇿🇦 rainbow nation colors',
dc_za_ep2_history: 'Ancient San rock art, Dutch ships arriving, Nelson Mandela walking free, rainbow nation celebration, Rugby World Cup trophy, South African flag in timeline, hope and resilience',
dc_za_ep3_places: 'Table Mountain from the sea, Kruger Park safari jeep with elephants, Cape of Good Hope lighthouse, Robben Island, Johannesburg skyline with gold mines, South African flag prominent',
dc_za_ep4_culture: 'Braai (BBQ) with boerewors, rugby ball, traditional Zulu beadwork, township music, bunny chow dish, 11 official languages shown, South African flag 🇿🇦, diverse and vibrant',
dc_za_ep5_facts: 'Fun illustration of a penguin at Boulders Beach (African penguins!), Big Five animals lined up, two oceans meeting, 11 languages as speech bubbles, gold nugget, around South African flag',
dc_tr_ep1_geo: 'Turkey bridging Europe and Asia with Istanbul straddling the Bosphorus strait, Cappadocia hot air balloons, turquoise Mediterranean coast, snowy Mount Ararat, Turkish flag 🇹🇷 crescent and star',
dc_tr_ep2_history: 'Hagia Sophia transformations (church-mosque-museum), Ottoman Sultan, ancient Troy wooden horse, Ataturk modernizing, Silk Road caravans, Turkish flag in timeline, crossroads of civilization',
dc_tr_ep3_places: 'Hagia Sophia golden dome, Cappadocia fairy chimneys with hot air balloons, Blue Mosque minarets, Pamukkale white terraces with blue pools, ancient Ephesus ruins, Turkish flag prominent',
dc_tr_ep4_culture: 'Turkish tea in tulip glass, kebab plate, whirling dervish spinning, Turkish carpet weaving, a hammam (bath house), Turkish delight sweets, Turkish flag 🇹🇷, warm hospitality',
dc_tr_ep5_facts: 'Fun illustration of a cat (Istanbul is city of cats!), tulips originated in Turkey not Holland, Santa Claus born in Turkey, cherry named after Turkish city, Bosphorus bridge connecting continents, around Turkish flag',
dc_ae_ep1_geo: 'Dubai skyline with Burj Khalifa towering over everything, golden desert dunes, Arabian Gulf turquoise water, Abu Dhabi mosque, oasis with palm trees, UAE flag 🇦🇪 green-white-black-red',
dc_ae_ep2_history: 'Bedouin tent in desert, pearl diving boats, oil discovery fountain, Sheikh Zayed vision, Dubai before-and-after (desert to skyscrapers), UAE flag in timeline, transformation story',
dc_ae_ep3_places: 'Burj Khalifa piercing clouds, Sheikh Zayed Grand Mosque in white marble, Palm Jumeirah island from above, Dubai Frame, Louvre Abu Dhabi, UAE flag prominent, futuristic and grand',
dc_ae_ep4_culture: 'Arabic coffee (gahwa) and dates, falcon on a glove, traditional kandura dress, camel racing, gold souk market, Emirati hospitality, UAE flag 🇦🇪, tradition meets luxury',
dc_ae_ep5_facts: 'Fun illustration of Burj Khalifa height comparison with other buildings, indoor skiing in the desert, a gold ATM machine, worlds fastest police cars, artificial islands from space, around UAE flag',
dc_es_ep1_geo: 'Spain landscape with Pyrenees mountains, golden plains of Castile, Mediterranean coast, Canary Islands volcanic, olive groves, Barcelona from above, Spanish flag 🇪🇸 red and yellow',
dc_es_ep2_history: 'Roman aqueduct of Segovia, Moorish Alhambra palace, Columbus ships sailing, Spanish galleon, Gaudi starting Sagrada Familia, Spanish flag in timeline, conquest and creativity',
dc_es_ep3_places: 'Sagrada Familia with colorful light inside, Alhambra palace gardens, Plaza de Espana Seville, Park Guell mosaic, Running of the Bulls Pamplona, Spanish flag prominent, artistic and passionate',
dc_es_ep4_culture: 'Paella in a huge pan, flamenco dancer with red dress, a football (La Liga), siesta hammock, tapas plates, a guitar being strummed, Spanish flag 🇪🇸, passionate and lively',
dc_es_ep5_facts: 'Fun illustration of a bull (friendly) eating paella, Sagrada Familia still being built since 1882, Spain has no tooth fairy but a tooth mouse, La Tomatina tomato fight, olive oil rivers, around Spanish flag',
dc_nz_ep1_geo: 'New Zealand two islands from above, snow-capped Southern Alps, geothermal hot springs steaming, lush green hobbit-like hills, fjords with waterfalls, Maori carving, NZ flag 🇳🇿',
dc_nz_ep2_history: 'Maori waka (canoe) arriving, haka war dance, Treaty of Waitangi signing, sheep farming origins, Edmund Hillary climbing Everest, NZ flag in timeline, indigenous and pioneer spirit',
dc_nz_ep3_places: 'Milford Sound fjord with waterfall, Hobbiton movie set green door, Sky Tower Auckland, geothermal Rotorua mud pools, Tongariro volcanic crossing, NZ flag prominent, Lord of the Rings landscapes',
dc_nz_ep4_culture: 'Haka dance with fierce expressions, hangi (earth oven) feast, rugby All Blacks, kiwi fruit and actual kiwi bird, pavlova dessert, Maori tattoo (ta moko), NZ flag 🇳🇿, brave and unique',
dc_nz_ep5_facts: 'Fun illustration of a kiwi bird next to a kiwi fruit (same name!), more sheep than people ratio, first country where women voted, bungee jumping invented here, no snakes in NZ, around NZ flag',

  // ══════ RAINBOW KINDERGARTEN EP4 ══════
  rk_ep4_summer: 'Splash pad water jets erupting in sunshine at a Toronto park, colorful bikes and scooters parked nearby, Lego bricks scattered under a tree, soccer ball on green grass, CN Tower in the background, warm summer golden hour, no human figures',

  // ══════ DISCOVER COUNTRIES — BATCH 1 KEY ALIASES ══════
  india_ep1_geo: 'Aerial view of India showing Himalayan mountains, green Ganges plains, golden Thar desert, blue Indian Ocean, Indian flag waving, warm storybook map style, no human figures',
  india_ep2_history: 'Ancient Indian monuments collage — Indus Valley ruins, Taj Mahal, ornate temple carvings, Ashoka pillar, timeline flowing left to right, Indian flag colors, storybook illustration, no human figures',
  india_ep3_places: 'Split panel showing Taj Mahal in moonlight, Red Fort at sunset, Golden Temple reflected in water, Gateway of India, Indian flag, warm watercolor, no human figures',
  india_ep4_culture: 'Colorful Holi powder colors flying, plates of biryani and samosas, cricket bat, sari fabrics, tabla drum, Indian flag prominently displayed, joyful celebration scene, no human figures',
  india_ep5_facts: 'Fun collage of tiger, ISRO rocket, chess board, mango tree, Bollywood film strip, arranged around Indian flag, colorful and playful, no human figures',
  canada_ep1_geo: 'Rocky Mountains with snow peaks, red canoe on turquoise lake, northern lights, maple trees in autumn orange, Canadian flag on mountain peak, breathtaking nature, no human figures',
  canada_ep2_history: 'Indigenous totem pole, voyageur canoe, Parliament building Ottawa, maple leaves falling, Canadian flag, warm storybook style, no human figures',
  canada_ep3_places: 'CN Tower Toronto, Niagara Falls rainbow, Parliament Hill Peace Tower, lighthouse on Atlantic coast, Banff mountains, Canadian flag, no human figures',
  canada_ep4_culture: 'Ice hockey sticks and puck, plate of poutine, maple syrup bottle on pancakes, Mountie hat, Canadian flag, cozy winter warmth, no human figures',
  canada_ep5_facts: 'Moose wearing toque, world longest coastline as wavy blue line, maple syrup jar, hockey stick, EN/FR signs, around Canadian flag, fun facts style, no human figures',
  usa_ep1_geo: 'Map-style aerial of USA showing Grand Canyon red, green eastern forests, golden California coast, snowy Rockies, Great Lakes blue, Statue of Liberty, American flag, no human figures',
  usa_ep2_history: 'Liberty Bell, Mayflower ship, Mount Rushmore, moon landing astronaut boot print, American flag weaving through timeline, historical illustration, no human figures',
  usa_ep3_places: 'Statue of Liberty, Golden Gate Bridge fog, Mount Rushmore, White House, Empire State Building, Disneyland castle, Route 66 road, American flag, no human figures',
  usa_ep4_culture: 'Baseball glove, plate of burgers and apple pie, jazz trumpet, Hollywood sign, NASA rocket, American flag, diverse and energetic collage, no human figures',
  usa_ep5_facts: 'Bald eagle, Moon with flag, basketball, hot dog, Grand Canyon depth comparison, 50 stars, arranged around American flag, playful, no human figures',
  uk_ep1_geo: 'British Isles aerial view, green rolling hills, Scottish Highlands purple heather, Welsh mountains, white cliffs of Dover, River Thames, Union Jack, misty and magical, no human figures',
  uk_ep2_history: 'Medieval castle, Viking ship, Big Ben and Parliament, Beatles Abbey Road crossing (shoes only), Union Jack weaving through timeline, no human figures',
  uk_ep3_places: 'Big Ben, Tower Bridge, Buckingham Palace guards hats, Stonehenge sunset, Edinburgh Castle, rainy sky with rainbow, Union Jack bunting, no human figures',
  uk_ep4_culture: 'Afternoon tea set with scones, red double-decker bus, football, wizard hat, corgi dog, fish and chips, beret, Union Jack flag, cozy British charm, no human figures',
  uk_ep5_facts: 'Corgi wearing tiny crown, Big Ben clock, red phone box, cups of tea, London Underground roundel, Shakespeare quill, Union Jack, fun facts style, no human figures',
  japan_ep1_geo: 'Mount Fuji with cherry blossoms foreground, bullet train passing, Japanese islands from above, ocean, bamboo forest, Japanese flag with rising sun, serene, no human figures',
  japan_ep2_history: 'Ancient wooden temple, samurai armor display, Himeji Castle, zen garden, origami cranes, Japanese flag in timeline, respectful illustration, no human figures',
  japan_ep3_places: 'Mount Fuji reflected in lake, Fushimi Inari red torii gates in row, Himeji Castle white, Tokyo Tower night, zen garden raked sand, cherry blossom petals, no human figures',
  japan_ep4_culture: 'Sushi plate with chopsticks, sumo ring, origami cranes, kimono fabric, martial arts dojo, cherry blossom festival, Japanese flag, colorful, no human figures',
  japan_ep5_facts: 'Bullet train with speed lines, vending machine, earthquake-proof building flexing, robot waving, 6852 islands as dots, Japanese flag, playful facts, no human figures',

  // ══════ DISCOVER COUNTRIES — HISTORY KEY ALIASES ══════
  dc_mx_ep2_hist: 'Aztec pyramid of Tenochtitlan, Mayan calendar stone, colonial Spanish church, Day of Dead sugar skull, Mexican flag in timeline, colorful illustration, no human figures',
  dc_it_ep2_hist: 'Roman Colosseum, Leonardo da Vinci flying machine sketch, Renaissance Florence dome, Galileo telescope, Italian flag timeline, golden classical, no human figures',
  dc_de_ep2_hist: 'Medieval castle Neuschwanstein, Gutenberg printing press, Brandenburg Gate, Berlin Wall painted with colorful art, VW Beetle, German flag timeline, no human figures',
  dc_kr_ep2_hist: 'Ancient Joseon palace, Korean turtle ship on ocean, Hangul alphabet characters floating, traditional hanbok dress display, Korean flag timeline, no human figures',
  dc_ru_ep2_hist: 'Kremlin Red Square, cosmonaut helmet in space, matryoshka dolls, Peter the Great ship, Faberge egg, Russian flag timeline, grand illustration, no human figures',
  dc_za_ep2_hist: 'Ancient San rock art on cave wall, Dutch sailing ship, rainbow nation flag colors, Rugby World Cup trophy, South African flag timeline, hope and resilience, no human figures',
  dc_tr_ep2_hist: 'Hagia Sophia golden dome transformation, Ottoman sultan tulip, ancient Troy wooden horse, Silk Road camels, Turkish flag crescent and star timeline, no human figures',
  dc_ae_ep2_hist: 'Bedouin tent in desert, pearl diving boats, oil discovery fountain, desert transforming to skyscrapers before-after, UAE flag timeline, no human figures',
  dc_es_ep2_hist: 'Roman aqueduct of Segovia, Moorish Alhambra palace arches, Columbus ships sailing, Spanish galleon, Gaudi Sagrada Familia, Spanish flag timeline, no human figures',
  dc_nz_ep2_hist: 'Maori waka canoe on ocean waves, haka performance shields, Treaty of Waitangi document, sheep on green hills, Mt Everest flag, NZ flag timeline, no human figures',

  // ══════ TALLEST TOWERS ══════
  tt_ep1_burj_khalifa: 'Burj Khalifa tower piercing through clouds at sunset, Dubai desert skyline, golden sand dunes in foreground, dramatic height perspective looking up, architectural watercolor, no human figures',
  tt_ep2_merdeka_118: 'Merdeka 118 tower soaring above Kuala Lumpur skyline, tropical clouds, Petronas Towers visible nearby, lush green palm trees, dramatic perspective, no human figures',
  tt_ep3_shanghai_tower: 'Shanghai Tower with its distinctive twisting glass design, Pudong skyline, Huangpu River below, dramatic clouds, futuristic cityscape, architectural illustration, no human figures',
  tt_ep4_abraj_al_bait: 'Abraj Al-Bait Clock Tower with enormous clock face glowing gold, Mecca skyline at night, crescent moon above, ornate Islamic architecture, dramatic scale, no human figures',
  tt_ep5_ping_an: 'Ping An Finance Centre sleek silver tower in Shenzhen skyline, modern Chinese city lights, evening blue hour, reflective glass facade, architectural elegance, no human figures',
  tt_ep6_lotte_world_tower: 'Lotte World Tower elegant cone shape in Seoul skyline, cherry blossoms in foreground, Han River reflection, Korean traditional roof tiles nearby, twilight, no human figures',
  tt_ep7_one_world_trade: 'One World Trade Center Freedom Tower gleaming in New York City skyline, Statue of Liberty in distance, American flag reflection in glass, sunrise, resilience and hope, no human figures',
  tt_ep8_guangzhou_ctf: 'Guangzhou CTF Finance Centre tall golden tower in Guangzhou skyline, Pearl River below, colorful city lights, dramatic evening sky, architectural watercolor, no human figures',
  tt_ep9_tianjin_ctf: 'Tianjin CTF Finance Centre modern tower in Tianjin cityscape, Hai River, mix of traditional and modern architecture, blue sky with dramatic clouds, no human figures',
  tt_ep10_citic_tower: 'CITIC Tower (China Zun) distinctive shape in Beijing skyline, Forbidden City rooftops visible below, mountains in background, golden hour, imperial meets modern, no human figures',
  tt_ep11_taipei_101: 'Taipei 101 bamboo-inspired segmented tower rising above Taipei city, green mountains behind, fireworks around the tower, night celebration, architectural marvel, no human figures',
  tt_ep12_shanghai_wfc: 'Shanghai World Financial Center with distinctive bottle-opener top opening, Shanghai skyline, Oriental Pearl Tower nearby, dramatic clouds through the aperture, no human figures',
  tt_ep13_icc_hong_kong: 'International Commerce Centre tower in Hong Kong harbor, Victoria Peak backdrop, traditional junk boats in harbor below, neon city lights, dramatic waterfront, no human figures',
  tt_ep14_petronas_towers: 'Petronas Twin Towers connected by skybridge, Kuala Lumpur, Islamic geometric patterns on facade, fountain park below, moonlit night, iconic twins, no human figures',
  tt_ep15_cn_tower: 'CN Tower tall needle against Toronto skyline, Lake Ontario below, Rogers Centre dome, autumn maple leaves floating, Canadian sunset orange and purple, iconic landmark, no human figures',
  tt_ep16_tokyo_skytree: 'Tokyo Skytree lattice tower illuminated in blue and purple, traditional Japanese temple in foreground, cherry blossoms, Tokyo city lights stretching to horizon, no human figures',
  tt_ep17_canton_tower: 'Canton Tower with twisting waist design illuminated in rainbow colors at night, Pearl River reflection, Guangzhou skyline, dramatic architectural lighting, no human figures',
  tt_ep18_ostankino_tower: 'Ostankino Tower tall needle in Moscow winter scene, snow falling, colorful St Basils Cathedral nearby, Soviet-era architecture meets modern, dramatic cold sky, no human figures',
  tt_ep19_willis_tower: 'Willis Tower (Sears Tower) black steel tower in Chicago skyline, glass Skydeck ledge extending from side, Lake Michigan below, dramatic clouds, architectural power, no human figures',
  tt_ep20_empire_state: 'Empire State Building art deco crown glowing gold at dusk, New York City stretching in all directions, vintage airplanes circling, classic movie poster style, iconic and timeless, no human figures',

};


// Get prompt for a story (with style prefix)
export function getStoryPrompt(storyId, style = 'thumbnail') {
  const scene = STORY_PROMPTS[storyId];
  if (!scene) return `${STYLES[style]}. Scene: A magical bedtime story illustration with warm golden light`;
  return buildPrompt(scene, style);
}