// AUTO-GENERATED by scripts/generate-share-titles.mjs — DO NOT EDIT BY HAND.
// Source: client/src/data/culturalLessons.js (211 wisdom stories).
// Consumed by api/share.js to build social/OG previews for shared story links.
export const WISDOM_TITLES = {
  "multilingual_lion_mouse": {
    "title": "The Lion and the Mouse — 9 Languages",
    "tradition": "Universal",
    "duration": 5
  },
  "krishna_squirrel": {
    "title": "Krishna and the Little Squirrel",
    "tradition": "Hindu",
    "duration": 10
  },
  "prophet_camel": {
    "title": "The Prophet and the Crying Camel",
    "tradition": "Muslim",
    "duration": 10
  },
  "jesus_birds": {
    "title": "Jesus and the Birds of the Air",
    "tradition": "Christian",
    "duration": 10
  },
  "buddha_swan": {
    "title": "Prince Siddhartha and the Wounded Swan",
    "tradition": "Buddhist",
    "duration": 10
  },
  "guru_nanak_grain": {
    "title": "Guru Nanak and the True Bargain",
    "tradition": "Sikh",
    "duration": 10
  },
  "mahavir_ant": {
    "title": "The Path of the Tiny Ant",
    "tradition": "Jain",
    "duration": 10
  },
  "jewish_noah": {
    "title": "Noah and the Animals of the Ark",
    "tradition": "Jewish",
    "duration": 10
  },
  "sikh_water_carrier": {
    "title": "Bhai Kanhaiya and the Cup of Water",
    "tradition": "Sikh",
    "duration": 10
  },
  "hanuman_mountain": {
    "title": "Hanuman and the Mountain of Herbs",
    "tradition": "Hindu",
    "duration": 10
  },
  "ram_golden_deer": {
    "title": "Ram and the Golden Deer",
    "tradition": "Hindu",
    "duration": 10
  },
  "akbar_birbal_well": {
    "title": "Akbar, Birbal, and the Well That Swallowed Water",
    "tradition": "Hindu",
    "duration": 10
  },
  "panchatantra_monkey_crocodile": {
    "title": "The Monkey and the Crocodile",
    "tradition": "Hindu",
    "duration": 10
  },
  "panchatantra_crow_pitcher": {
    "title": "The Thirsty Crow",
    "tradition": "Hindu",
    "duration": 8
  },
  "krishna_govardhan": {
    "title": "Krishna and the Mountain Shield",
    "tradition": "Hindu",
    "duration": 10
  },
  "akbar_birbal_lines": {
    "title": "Birbal and the Shorter Line",
    "tradition": "Hindu",
    "duration": 8
  },
  "ganesha_mouse": {
    "title": "Ganesha and the Little Mouse",
    "tradition": "Hindu",
    "duration": 8
  },
  "hindu_cow_sage": {
    "title": "The Sage and the Injured Deer",
    "tradition": "Hindu",
    "duration": 8
  },
  "krishna_butter": {
    "title": "Krishna and the Pot of Butter",
    "tradition": "Hindu",
    "duration": 10
  },
  "harishchandra_promise": {
    "title": "King Harishchandra and the Promise",
    "tradition": "Hindu",
    "duration": 10
  },
  "yudhishthira_half_truth": {
    "title": "Yudhishthira and the Chariot That Sank",
    "tradition": "Hindu",
    "duration": 9
  },
  "sudama_poha": {
    "title": "Sudama and the Handful of Poha",
    "tradition": "Hindu",
    "duration": 10
  },
  "draupadi_akshaya_patra": {
    "title": "Draupadi and the Vessel That Never Emptied",
    "tradition": "Hindu",
    "duration": 9
  },
  "karna_golden_armour": {
    "title": "Karna and the Golden Armour",
    "tradition": "Hindu",
    "duration": 10
  },
  "ram_shabari_berries": {
    "title": "Ram and Shabari's Half-Eaten Berries",
    "tradition": "Hindu",
    "duration": 9
  },
  "hanuman_chest": {
    "title": "Hanuman's Heart",
    "tradition": "Hindu",
    "duration": 8
  },
  "shiva_kannappa": {
    "title": "Kannappa and the Eyes of Devotion",
    "tradition": "Hindu",
    "duration": 9
  },
  "ram_vibhishana": {
    "title": "Ram and the Enemy's Brother",
    "tradition": "Hindu",
    "duration": 9
  },
  "sage_scorpion": {
    "title": "The Sage and the Scorpion",
    "tradition": "Hindu",
    "duration": 7
  },
  "krishna_hundred_chances": {
    "title": "Krishna and the Hundred Chances",
    "tradition": "Hindu",
    "duration": 9
  },
  "prophet_ant_hill": {
    "title": "The Prophet and the Ant Hill",
    "tradition": "Muslim",
    "duration": 8
  },
  "prophet_thirsty_dog": {
    "title": "The Woman and the Thirsty Dog",
    "tradition": "Muslim",
    "duration": 8
  },
  "good_samaritan": {
    "title": "The Good Samaritan",
    "tradition": "Christian",
    "duration": 9
  },
  "jesus_mustard_seed": {
    "title": "The Tiny Mustard Seed",
    "tradition": "Christian",
    "duration": 7
  },
  "buddha_elephant": {
    "title": "Buddha and the Angry Elephant",
    "tradition": "Buddhist",
    "duration": 8
  },
  "buddha_rice_bowl": {
    "title": "The Buddha and the Golden Rice Bowl",
    "tradition": "Buddhist",
    "duration": 7
  },
  "jain_true_wealth": {
    "title": "The Merchant Who Gave Everything",
    "tradition": "Jain",
    "duration": 8
  },
  "jain_spider_web": {
    "title": "The Spider's Beautiful Web",
    "tradition": "Jain",
    "duration": 3
  },
  "jewish_one_good_deed": {
    "title": "The Boy Who Fixed the World",
    "tradition": "Jewish",
    "duration": 8
  },
  "jewish_two_pockets": {
    "title": "The Two Pockets",
    "tradition": "Jewish",
    "duration": 7
  },
  "sikh_langar": {
    "title": "Guru Nanak and the Langar",
    "tradition": "Sikh",
    "duration": 8
  },
  "mothers_day_toronto": {
    "title": "The Tulips That Said Thank You",
    "tradition": "Universal",
    "duration": 8
  },
  "universal_lighthouse_keeper": {
    "title": "The Lighthouse Keeper Who Was Afraid of Storms",
    "tradition": "Universal",
    "duration": 8
  },
  "universal_garden_of_mistakes": {
    "title": "The Garden Where Mistakes Grew Flowers",
    "tradition": "Universal",
    "duration": 7
  },
  "universal_invisible_boy": {
    "title": "The Invisible Boy and the Stray Dog",
    "tradition": "Universal",
    "duration": 8
  },
  "universal_patience_river": {
    "title": "The River That Carved a Canyon",
    "tradition": "Universal",
    "duration": 7
  },
  "universal_sharing_blanket": {
    "title": "The Blanket That Grew",
    "tradition": "Universal",
    "duration": 7
  },
  "universal_respect_old_tree": {
    "title": "The Oldest Tree in Town",
    "tradition": "Universal",
    "duration": 8
  },
  "universal_forgiveness_kite": {
    "title": "The Boy Who Let Go of the String",
    "tradition": "Universal",
    "duration": 7
  },
  "universal_wisdom_two_wolves": {
    "title": "The Two Wolves Inside You",
    "tradition": "Universal",
    "duration": 6
  },
  "universal_humility_mountain": {
    "title": "The Mountain That Learned to Bow",
    "tradition": "Universal",
    "duration": 7
  },
  "universal_bravery_first_step": {
    "title": "The Girl Who Walked Into the Dark",
    "tradition": "Universal",
    "duration": 7
  },
  "coqui_rainforest": {
    "title": "El Coquí and the Thirsty Orchid",
    "tradition": "Hispanic",
    "duration": 5
  },
  "quetzal_feather": {
    "title": "The Quetzal Who Gave Its Feathers",
    "tradition": "Hispanic",
    "duration": 5
  },
  "abuela_monarch": {
    "title": "Abuela and the Monarch Butterflies",
    "tradition": "Hispanic",
    "duration": 5
  },
  "ixchel_rainbow": {
    "title": "Ixchel and the Broken Rainbow",
    "tradition": "Hispanic",
    "duration": 5
  },
  "child_hurricane": {
    "title": "The Night of the Big Wind",
    "tradition": "Hispanic",
    "duration": 5
  },
  "quetzalcoatl_sun": {
    "title": "Quetzalcoatl and the Gift of the Sun",
    "tradition": "Hispanic",
    "duration": 5
  },
  "pinata_truth": {
    "title": "The Piñata That Told the Truth",
    "tradition": "Hispanic",
    "duration": 5
  },
  "mercado_coin": {
    "title": "The Extra Coin at the Mercado",
    "tradition": "Hispanic",
    "duration": 5
  },
  "tamale_patience": {
    "title": "Abuela's Tamales Take Time",
    "tradition": "Hispanic",
    "duration": 5
  },
  "andes_farmer": {
    "title": "The Farmer and the Andean Terrace",
    "tradition": "Hispanic",
    "duration": 5
  },
  "ofrenda_gratitude": {
    "title": "The Ofrenda on the Kitchen Table",
    "tradition": "Hispanic",
    "duration": 5
  },
  "cafecito_gracias": {
    "title": "Papá's Cafecito at Sunrise",
    "tradition": "Hispanic",
    "duration": 5
  },
  "tres_reyes_sharing": {
    "title": "The Three Kings and the Shoe by the Door",
    "tradition": "Hispanic",
    "duration": 5
  },
  "empanada_sharing": {
    "title": "The Last Empanada",
    "tradition": "Hispanic",
    "duration": 5
  },
  "community_garden": {
    "title": "The Garden That Fed the Block",
    "tradition": "Hispanic",
    "duration": 5
  },
  "bendicion_respect": {
    "title": "The Blessing at the Door",
    "tradition": "Hispanic",
    "duration": 5
  },
  "elder_ceiba": {
    "title": "The Elder and the Ceiba Tree",
    "tradition": "Hispanic",
    "duration": 5
  },
  "llorona_brave": {
    "title": "The Girl Who Sang to La Llorona",
    "tradition": "Hispanic",
    "duration": 5
  },
  "first_day_escuela": {
    "title": "The First Day in a New Escuela",
    "tradition": "Hispanic",
    "duration": 5
  },
  "rabbit_moon_wisdom": {
    "title": "The Rabbit on the Moon",
    "tradition": "Hispanic",
    "duration": 5
  },
  "abuela_dichos": {
    "title": "Abuela's Box of Dichos",
    "tradition": "Hispanic",
    "duration": 5
  },
  "soccer_humility": {
    "title": "The Soccer Star Who Swept the Field",
    "tradition": "Hispanic",
    "duration": 5
  },
  "virgen_guadalupe_roses": {
    "title": "Juan Diego and the Roses on the Hill",
    "tradition": "Hispanic",
    "duration": 5
  },
  "hermanos_forgive": {
    "title": "The Two Brothers and the Mango Tree",
    "tradition": "Hispanic",
    "duration": 5
  },
  "fiesta_apology": {
    "title": "The Apology at the Fiesta",
    "tradition": "Hispanic",
    "duration": 5
  },
  "francis_wolf": {
    "title": "Saint Francis and the Wolf of Gubbio",
    "tradition": "Catholic",
    "duration": 5
  },
  "francis_birds_sermon": {
    "title": "Saint Francis Preaches to the Birds",
    "tradition": "Catholic",
    "duration": 5
  },
  "joan_arc_voices": {
    "title": "Joan and the Voices in the Garden",
    "tradition": "Catholic",
    "duration": 5
  },
  "daniel_lions": {
    "title": "Daniel and the Den of Lions",
    "tradition": "Catholic",
    "duration": 5
  },
  "augustine_pears": {
    "title": "Young Augustine and the Pear Tree",
    "tradition": "Catholic",
    "duration": 5
  },
  "peter_rooster": {
    "title": "Peter and the Rooster at Dawn",
    "tradition": "Catholic",
    "duration": 5
  },
  "zacchaeus_tree": {
    "title": "Zacchaeus in the Sycamore Tree",
    "tradition": "Catholic",
    "duration": 5
  },
  "advent_candles": {
    "title": "The Four Candles of Advent",
    "tradition": "Catholic",
    "duration": 5
  },
  "monica_prayer": {
    "title": "Saint Monica and the Thirty-Year Prayer",
    "tradition": "Catholic",
    "duration": 5
  },
  "ten_lepers": {
    "title": "The One Who Came Back",
    "tradition": "Catholic",
    "duration": 5
  },
  "magnificat_song": {
    "title": "Mary's Song of Thankfulness",
    "tradition": "Catholic",
    "duration": 5
  },
  "loaves_fishes": {
    "title": "The Boy with Five Loaves and Two Fish",
    "tradition": "Catholic",
    "duration": 5
  },
  "martin_cloak": {
    "title": "Saint Martin and the Beggar's Cloak",
    "tradition": "Catholic",
    "duration": 5
  },
  "jesus_children": {
    "title": "Let the Children Come",
    "tradition": "Catholic",
    "duration": 5
  },
  "nicholas_gifts": {
    "title": "Saint Nicholas and the Secret Gifts",
    "tradition": "Catholic",
    "duration": 5
  },
  "david_goliath": {
    "title": "David and the Giant",
    "tradition": "Catholic",
    "duration": 5
  },
  "teresa_calcutta": {
    "title": "Mother Teresa and the Smallest Act",
    "tradition": "Catholic",
    "duration": 5
  },
  "prodigal_son": {
    "title": "The Father Who Waited at the Gate",
    "tradition": "Catholic",
    "duration": 5
  },
  "solomon_baby": {
    "title": "King Solomon and the Two Mothers",
    "tradition": "Catholic",
    "duration": 5
  },
  "jesus_feet_washing": {
    "title": "The King Who Washed Feet",
    "tradition": "Catholic",
    "duration": 5
  },
  "therese_little_way": {
    "title": "The Little Way of Saint Thérèse",
    "tradition": "Catholic",
    "duration": 5
  },
  "christmas_manger": {
    "title": "The King Born in a Stable",
    "tradition": "Catholic",
    "duration": 5
  },
  "good_thief": {
    "title": "The Thief Who Was Forgiven Last",
    "tradition": "Catholic",
    "duration": 5
  },
  "joseph_brothers": {
    "title": "Joseph and His Brothers",
    "tradition": "Catholic",
    "duration": 5
  },
  "lost_sheep": {
    "title": "The Shepherd and the One Lost Sheep",
    "tradition": "Catholic",
    "duration": 5
  },
  "fil_maria_makiling": {
    "title": "Maria Makiling — Guardian of the Mountain",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_monkey_turtle": {
    "title": "The Monkey and the Turtle",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_bayanihan": {
    "title": "Bayanihan — The House That Moved",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_alitaptap": {
    "title": "Alitaptap — The Legend of the Firefly",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_malakas_maganda": {
    "title": "Malakas and Maganda — Born from Bamboo",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_sampaguita": {
    "title": "The Legend of the Sampaguita",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_lola_wisdom": {
    "title": "Lola's Wisdom by the Stove",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_sarimanok": {
    "title": "Sarimanok — The Magical Bird of Mindanao",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_mano_po": {
    "title": "The Gift of Mano Po",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_fiesta": {
    "title": "The Fiesta That Fed the Whole Barangay",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_carabao": {
    "title": "The Carabao — A Farmer's Best Friend",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_bahay_kubo": {
    "title": "Bahay Kubo — The Nipa Hut and Its Garden",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_pineapple": {
    "title": "The Legend of the Pineapple",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_tinikling": {
    "title": "The Tinikling Dance",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_first_banana": {
    "title": "The Story of the First Banana",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_hospitality": {
    "title": "The Door That Was Always Open",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_mango_legend": {
    "title": "The Legend of the Mango",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_golden_fish": {
    "title": "The Fisherman and the Golden Fish",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_tala_stars": {
    "title": "Tala and the Stars",
    "tradition": "Filipino",
    "duration": 5
  },
  "fil_juan_tamad": {
    "title": "Juan Tamad and the Guava Tree",
    "tradition": "Filipino",
    "duration": 5
  },
  "mus_prophet_kindness": {
    "title": "The Prophet and the Hungry Cat",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_ibrahim_stars": {
    "title": "Ibrahim and the Stars",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_yusuf_patience": {
    "title": "Yusuf and the Deep Well",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_nuh_ark": {
    "title": "Nuh and the Great Ark",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_sulaiman_ant": {
    "title": "Sulaiman and the Little Ant",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_bilal_call": {
    "title": "Bilal and the First Call to Prayer",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_khadijah_support": {
    "title": "Khadijah — The First to Believe",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_spider_cave": {
    "title": "The Spider at the Cave",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_date_palm": {
    "title": "The Crying Date Palm",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_hungry_neighbor": {
    "title": "The Neighbor Who Was Always Fed First",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_well_zamzam": {
    "title": "Baby Ismail and the Well of Zamzam",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_mercy_birds": {
    "title": "The Prophet and the Mother Bird",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_honest_merchant": {
    "title": "The Honest Merchant",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_forgiveness_makkah": {
    "title": "The Day Makkah Was Opened",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_ramadan_moon": {
    "title": "The First Ramadan Moon",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_garden_brothers": {
    "title": "The Owners of the Garden",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_sleepers_cave": {
    "title": "The Sleepers of the Cave",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_mother_paradise": {
    "title": "Paradise Lies at the Feet of Your Mother",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_two_brothers_field": {
    "title": "The Two Brothers and the Wheat Field",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_barakah_bismillah": {
    "title": "Saying Bismillah Before Everything",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_prophet_smile": {
    "title": "The Prophet's Smile",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_trust_allah_camel": {
    "title": "Trust in Allah, but Tie Your Camel",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_cleaning_path": {
    "title": "Removing Harm from the Path",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_aisha_generosity": {
    "title": "Aisha and Her Last Meal",
    "tradition": "Muslim",
    "duration": 5
  },
  "mus_luqman_wisdom": {
    "title": "Luqman's Advice to His Son",
    "tradition": "Muslim",
    "duration": 5
  },
  "sikh_river_teaches": {
    "title": "The River That Teaches",
    "tradition": "Sikh",
    "duration": 3
  },
  "sikh_needle_thread": {
    "title": "The Needle and the Thread",
    "tradition": "Sikh",
    "duration": 3
  },
  "sikh_bhai_lalo_bread": {
    "title": "Bhai Lalo's Simple Bread",
    "tradition": "Sikh",
    "duration": 3
  },
  "sikh_jasmine_garden": {
    "title": "The Jasmine Garden",
    "tradition": "Sikh",
    "duration": 3
  },
  "sikh_cobbler_prayer": {
    "title": "The Cobbler's Prayer",
    "tradition": "Sikh",
    "duration": 3
  },
  "sikh_milk_jasmine": {
    "title": "The Milk and the Jasmine",
    "tradition": "Sikh",
    "duration": 3
  },
  "sikh_two_swords": {
    "title": "Two Swords, One Heart",
    "tradition": "Sikh",
    "duration": 3
  },
  "sikh_bhai_kanhaiya": {
    "title": "The Boy Who Served Water to All",
    "tradition": "Sikh",
    "duration": 3
  },
  "sikh_mata_khivi_langar": {
    "title": "Mata Khivi and the Blessed Langar",
    "tradition": "Sikh",
    "duration": 3
  },
  "sikh_youngest_guru": {
    "title": "The Youngest Guru",
    "tradition": "Sikh",
    "duration": 3
  },
  "sikh_lion_roars": {
    "title": "Why the Lion Roars",
    "tradition": "Sikh",
    "duration": 3
  },
  "sikh_string_of_kite": {
    "title": "The String of the Kite",
    "tradition": "Sikh",
    "duration": 3
  },
  "sikh_guru_ka_langar": {
    "title": "Guru Ka Langar — No One Goes Hungry",
    "tradition": "Sikh",
    "duration": 3
  },
  "sikh_sound_waheguru": {
    "title": "The Sound of Waheguru",
    "tradition": "Sikh",
    "duration": 3
  },
  "sikh_stars_amritsar": {
    "title": "Stars Over Amritsar",
    "tradition": "Sikh",
    "duration": 3
  },
  "indigenous_eagle_feather": {
    "title": "The Eagle Feather",
    "tradition": "Indigenous",
    "duration": 5
  },
  "indigenous_two_eyed_seeing": {
    "title": "Two-Eyed Seeing",
    "tradition": "Indigenous",
    "duration": 5
  },
  "indigenous_medicine_wheel": {
    "title": "The Medicine Wheel",
    "tradition": "Indigenous",
    "duration": 5
  },
  "indigenous_river_knows": {
    "title": "The River Knows the Way",
    "tradition": "Indigenous",
    "duration": 5
  },
  "indigenous_fire_keeper": {
    "title": "The Fire Keeper",
    "tradition": "Indigenous",
    "duration": 5
  },
  "indigenous_cedar_sage_sweetgrass": {
    "title": "Cedar, Sage, Sweetgrass",
    "tradition": "Indigenous",
    "duration": 5
  },
  "indigenous_moose_mouse": {
    "title": "The Moose and the Mouse",
    "tradition": "Indigenous",
    "duration": 5
  },
  "indigenous_snow_silence": {
    "title": "Snow Teaches Silence",
    "tradition": "Indigenous",
    "duration": 5
  },
  "indigenous_northern_lights": {
    "title": "The Northern Lights Dance",
    "tradition": "Indigenous",
    "duration": 5
  },
  "indigenous_every_rock": {
    "title": "Every Rock Has a Story",
    "tradition": "Indigenous",
    "duration": 5
  },
  "christian_shepherd_blanket": {
    "title": "The Shepherd Boy's Blanket",
    "tradition": "Christian",
    "duration": 3
  },
  "christian_fisherman_net": {
    "title": "The Fisherman's Net",
    "tradition": "Christian",
    "duration": 3
  },
  "christian_sparrow_watches": {
    "title": "The Sparrow God Watches",
    "tradition": "Christian",
    "duration": 3
  },
  "christian_star_led_way": {
    "title": "The Star That Led the Way",
    "tradition": "Christian",
    "duration": 3
  },
  "christian_well_living_water": {
    "title": "The Well of Living Water",
    "tradition": "Christian",
    "duration": 3
  },
  "christian_fig_tree_chance": {
    "title": "The Fig Tree's Second Chance",
    "tradition": "Christian",
    "duration": 3
  },
  "christian_mustard_seed_garden": {
    "title": "The Mustard Seed Garden",
    "tradition": "Christian",
    "duration": 3
  },
  "christian_widow_coins": {
    "title": "The Widow's Two Coins",
    "tradition": "Christian",
    "duration": 3
  },
  "christian_bridges_not_walls": {
    "title": "Building Bridges, Not Walls",
    "tradition": "Christian",
    "duration": 3
  },
  "christian_light_on_hill": {
    "title": "The Light on the Hill",
    "tradition": "Christian",
    "duration": 3
  },
  "buddhist_tiger_strawberry": {
    "title": "The Tiger and the Strawberry",
    "tradition": "Buddhist",
    "duration": 3
  },
  "buddhist_empty_cup": {
    "title": "The Empty Cup",
    "tradition": "Buddhist",
    "duration": 3
  },
  "buddhist_siddhartha_garden": {
    "title": "Siddhartha's Garden",
    "tradition": "Buddhist",
    "duration": 3
  },
  "buddhist_monk_scorpion": {
    "title": "The Monk and the Scorpion",
    "tradition": "Buddhist",
    "duration": 3
  },
  "buddhist_mountain_moved": {
    "title": "The Mountain That Moved Slowly",
    "tradition": "Buddhist",
    "duration": 3
  },
  "buddhist_two_hands": {
    "title": "Two Hands Clapping",
    "tradition": "Buddhist",
    "duration": 3
  },
  "buddhist_river_found_sea": {
    "title": "The River That Found the Sea",
    "tradition": "Buddhist",
    "duration": 3
  },
  "buddhist_breathing_ocean": {
    "title": "Breathing Like the Ocean",
    "tradition": "Buddhist",
    "duration": 3
  },
  "buddhist_farmer_good_luck": {
    "title": "The Farmer's Good Luck",
    "tradition": "Buddhist",
    "duration": 3
  },
  "buddhist_footprints_snow": {
    "title": "Footprints in the Snow",
    "tradition": "Buddhist",
    "duration": 3
  },
  "jain_prince_never_hurt_fly": {
    "title": "The Prince Who Never Hurt a Fly",
    "tradition": "Jain",
    "duration": 3
  },
  "jain_merchant_gave_everything": {
    "title": "The Merchant Who Gave Everything",
    "tradition": "Jain",
    "duration": 3
  },
  "jain_bird_carried_water": {
    "title": "The Bird That Carried Water",
    "tradition": "Jain",
    "duration": 3
  },
  "jain_walking_barefoot": {
    "title": "Walking Barefoot",
    "tradition": "Jain",
    "duration": 3
  },
  "jain_diamond_dewdrop": {
    "title": "The Diamond and the Dewdrop",
    "tradition": "Jain",
    "duration": 3
  },
  "jain_peacock_dance": {
    "title": "The Peacock's Dance",
    "tradition": "Jain",
    "duration": 3
  },
  "jain_farmer_fed_ants": {
    "title": "The Farmer Who Fed the Ants",
    "tradition": "Jain",
    "duration": 3
  },
  "jain_temple_sunrise": {
    "title": "The Jain Temple at Sunrise",
    "tradition": "Jain",
    "duration": 3
  },
  "jain_child_counted_stars": {
    "title": "The Child Who Counted Stars",
    "tradition": "Jain",
    "duration": 3
  },
  "jewish_wise_child_chelm": {
    "title": "The Wise Child of Chelm",
    "tradition": "Jewish",
    "duration": 3
  },
  "jewish_golem_heart": {
    "title": "The Golem's Heart",
    "tradition": "Jewish",
    "duration": 3
  },
  "jewish_ruth_naomi": {
    "title": "Ruth and Naomi's Promise",
    "tradition": "Jewish",
    "duration": 3
  },
  "jewish_apple_tree_road": {
    "title": "The Apple Tree at the End of the Road",
    "tradition": "Jewish",
    "duration": 3
  },
  "jewish_dreidel_spun": {
    "title": "The Dreidel That Spun All Night",
    "tradition": "Jewish",
    "duration": 3
  },
  "jewish_elijah_chair": {
    "title": "Elijah's Empty Chair",
    "tradition": "Jewish",
    "duration": 3
  },
  "jewish_box_beautiful_words": {
    "title": "The Box of Beautiful Words",
    "tradition": "Jewish",
    "duration": 3
  },
  "jewish_shabbat_candles": {
    "title": "The Shabbat Candles",
    "tradition": "Jewish",
    "duration": 3
  },
  "jewish_vineyard_kindness": {
    "title": "The Vineyard of Kindness",
    "tradition": "Jewish",
    "duration": 3
  },
  "jewish_hanukkah_flame": {
    "title": "Hanukkah's Smallest Flame",
    "tradition": "Jewish",
    "duration": 3
  }
};
